### ISSUE TITLE
"console.assert is not a function" when debugging after upgrading to 3.0.2

### ISSUE THREAD

**Issue by NiharR27** [software-mansion/react-native-reanimated#4354]
### Description

After upgrading from  "react-native-reanimated": "^2.14.4", to "react-native-reanimated": "^3.0.2", i am unable to debug.

I get this error:
```
e: TypeError: console.assert is not a function
    at pd (event-target-shim.js:46)
    at setPassiveListener (event-target-shim.js:487)
    at EventTarget.dispatchEvent (event-target-shim.js:812)
    at WebSocket.js:251
    at EventEmitter.emit (EventEmitter.js:105)
    at MessageQueue.__callFunction (MessageQueue.js:423)
    at MessageQueue.js:113
    at MessageQueue.__guard (MessageQueue.js:367)
    at MessageQueue.callFunctionReturnFlushedQueue (MessageQueue.js:112)
    at RNDebuggerWorker.js:2
```

downgrading back to 2.14.4 fixes the issue and debugger starts working back

Found similar threat on stack overflow: 
https://stackoverflow.com/questions/75689543/starting-debugger-error-console-assert-is-not-a-function and this 

possible similar issue on the project:
https://github.com/software-mansion/react-native-reanimated/issues/3951#issuecomment-1384223013

### Steps to reproduce

1. add react-native-reanimated: 3.0.2 (make sure to do pod install)
2. Start the app
3. Open debugger if you have (or use web debugger)
4. Debug
5. See the crash mentioned above

### Snack or a link to a repository

https://stackoverflow.com/questions/75689543/starting-debugger-error-console-assert-is-not-a-function

### Reanimated version

3.0.2

### React Native version

0.70.6

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Should be fixed with #4365
