### ISSUE TITLE
TypeError: interpolate is not a function. 

### ISSUE THREAD

**Issue by sandeepmahajan11** [software-mansion/react-native-reanimated#3663]
### Description

**When I updated reanimated version from 1.13.1 to 2.10.0 it gives runtime crash, Please see below details.**

**Error Log :** 
 ERROR  TypeError: interpolate is not a function. (In 'interpolate(this.progress, {
              inputRange: [PROGRESS_EPSILON, 1],
              outputRange: [0, 1]
            })', 'interpolate' is undefined)

This error is located at:
    in Drawer (created by DrawerView)
    in DrawerView (created by Navigator)
    in Navigator (created by SceneView)
    in SceneView (created by SwitchView)
    in SwitchView (created by Navigator)
    in Navigator (created by NavigationContainer)
    in NavigationContainer (created by App)
    in RCTView (created by View)
    in View (created by App)
    in ConfigProvider (created by App)
    in RCTSafeAreaView (created by App)
    in PersistGate (created by App)
    in Provider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in FireStorm(RootComponent)
 ERROR  TypeError: interpolate is not a function. (In 'interpolate(this.progress, {
              inputRange: [PROGRESS_EPSILON, 1],
              outputRange: [0, 1]
            })', 'interpolate' is undefined)

This error is located at:
    in NavigationContainer (created by App)
    in RCTView (created by View)
    in View (created by App)
    in ConfigProvider (created by App)
    in RCTSafeAreaView (created by App)
    in PersistGate (created by App)
    in Provider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in FireStorm(RootComponent)
 ERROR  TypeError: interpolate is not a function. (In 'interpolate(this.progress, {
              inputRange: [PROGRESS_EPSILON, 1],
              outputRange: [0, 1]
            })', 'interpolate' is undefined)

This error is located at:
    in NavigationContainer (created by App)
    in RCTView (created by View)
    in View (created by App)
    in ConfigProvider (created by App)
    in RCTSafeAreaView (created by App)
    in PersistGate (created by App)
    in Provider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in FireStorm(RootComponent)

//###############################################//

**React-Native Configuration :** 

System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 78.78 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.13.2 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 21, 30, 33
      Build Tools: 29.0.2, 33.0.0
      System Images: android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_302 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.70.1 => 0.70.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

install -
"react-native-reanimated": "2.10.0",
 "react-navigation-drawer": "2.7.2",

and run the project, after login it crashes.
<img width="1071" alt="Screenshot 2022-10-12 at 12 50 16 PM" src="https://user-images.githubusercontent.com/13939382/195296119-c9b147b7-7e20-43ac-92de-680e02a3630a.png">

### Snack or a link to a repository

https://snack.expo.io/

### Reanimated version

2.10.0

### React Native version

0.70.1

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone XR (Simulator)

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
See https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/migration
