### ISSUE TITLE
React Native 0.76 is not supported

### ISSUE THREAD

**Issue by fmorau** [software-mansion/react-native-reanimated#6574]
### Description

Hello!

The library is currently using a deprecated method `updateLayout` from the `NativeViewHierarchyManager class`, which was removed in the latest React Native 0.76 version (https://github.com/facebook/react-native/pull/45422).
This causes compilation errors when building the project with the latest React Native version.

### Steps to reproduce

1. Update your React Native project to version 0.76.0-rc.3
1. Attempt to build the project - (run "yarn android")
1. Observe the compilation errors related to the updateLayout method in ReanimatedNativeHierarchyManager.

### Snack or a link to a repository

https://github.com/fmorau/RN-0.76-reanimated-issue

### Reanimated version

3.15.4

### React Native version

0.76.0-rc.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

Android emulator

### Device model

any

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Hey, we've added a support for 0.76 in 3.16, so you just need to update the version of Reanimated 😃

**Comment by Mahmoudkhoder01** [comment]
> Hey, we've added a support for 0.76 in 3.16, so you just need to update the version of Reanimated 😃

but the issue still persist!!

**Comment by Rexogamer** [comment]
what issue are you facing? Reanimated works perfectly fine for me with RN v0.76

**Comment by denysoleksiienko** [comment]
Reanimated 3.16 works with lags on RN 0.76, even with a simple accordion that hides some data. I wanted to roll back to 3.15.1, which works perfectly, but it doesn’t work on Android with RN 0.76 (_error: no suitable method found for updateLayout(int,int,int,int,int,int)_), only with 0.75.

**Comment by Rexogamer** [comment]
please open a new issue for this - that sounds like a different bug
