### ISSUE TITLE
REANIMATED_VERSION_STRING

### ISSUE THREAD

**Issue by DanielRiera** [software-mansion/react-native-reanimated#4009]
### Description

When run `react-native run-ios --verbose` fail

`	CompileC /Users/xxxxxx/Library/Developer/Xcode/DerivedData/xxxx-xxxxxx/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNReanimated.build/Objects-normal/x86_64/ReanimatedVersion.o /Users/xxxxxx/Documents/xxxx/xxxx/node_modules/react-native-reanimated/Common/cpp/Tools/ReanimatedVersion.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNReanimated' from project 'Pods')
(1 failure)
`

If open project with Xcode 14.2 show the error "Use of undeclared identifier 'REANIMATED_VERSION_STRING'" on ReanimatedVersion.cpp.

### Steps to reproduce

1. run react-native run-ios

### Snack or a link to a repository

none

### Reanimated version

2.14.4

### React Native version

0.71

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @DanielRiera, thanks for reporting the issue. Unfortunately, I wasn't able to reproduce it as the app compiles successfully for me. Here are my steps:
```sh
npx react-native@next init MyApp --version 0.71.1 --skip-install
cd MyApp
yarn add react-native-reanimated@2.14.4
cd ios
pod install
yarn react-native run-ios --verbose
```
Did you remember to run `pod install` after upgrading to 2.14.4 and before building the app?

**Comment by DanielRiera** [comment]
I follow this steps https://github.com/facebook/react-native/issues/26118#issuecomment-525085809

its works

**Comment by anuragipankaj** [comment]
facing same issue, this issue should not be closed 

i'm using     "react-native-reanimated": "2.14.4", with     "react-native": "0.71.4",
error
../node_modules/react-native-reanimated/Common/cpp/Tools/ReanimatedVersion.cpp:14:42: error: use of undeclared identifier 'REANIMATED_VERSION_STRING'
  return jsi::String::createFromUtf8(rt, REANIMATED_VERSION_STRING);
                                         ^
1 error generated.

**Comment by anuragipankaj** [comment]
@DanielRiera any idea how to solve this?

**Comment by DanielRiera** [comment]
@anuragipankaj Try this https://github.com/facebook/react-native/issues/26118#issuecomment-525085809

**Comment by ammichael** [comment]
I still have this issue. 

"react-native-reanimated": "^3.1.0"
"react-native": "^0.67.4"

Already tried the comment you pointed out @DanielRiera, but no lucky.
Any ideas?

**Comment by DanielRiera** [comment]
Try compile with XCode, and your see errors. 

Check your Pods sdk version

**Comment by dorkycam** [comment]
@ammichael Have you had any luck? I've come across this issue too

"react-native-reanimated": "^3.3.0"
"react-native": "0.71.6"

**Comment by salah-ghanim** [comment]
The problem in our case was that our project's Podfile included a post_install script that removed all C++ flags (must have been needed for a specific RN version).

once removed

`config.build_settings['OTHER_CPLUSPLUSFLAGS'] = ''`

 and the project is cleaned:
```
 * rm -rf Pods/*
 * rm Podfile.lock
 * pod deintegrate
 * pod setup
 * pod install
```

it worked.

I would recommend of course that you clean the derivedData folder as well.

**Comment by digthedill** [comment]
+1 still not working for me.

RN: 0.72.3
react-native-reanimated: ^3.4.2

**Comment by akuera** [comment]
@digthedill Came across this issue today. I had to make version changes

```
"react-native-reanimated": "^3.3.0"
"react-native": "0.71.6"
```

`yarn install` || `npm install`
`npx post-install` || `cd ios && pod install`

**Comment by ahmedragab-rawasi** [comment]
+1 not working for me either.

"react-native": "0.72.3"

**Comment by julianD77** [comment]
> The problem in our case was that our project's Podfile included a post_install script that removed all C++ flags (must have been needed for a specific RN version).
> 
> once removed
> 
> `config.build_settings['OTHER_CPLUSPLUSFLAGS'] = ''`
> 
> and the project is cleaned:
> 
> ```
>  * rm -rf Pods/*
>  * rm Podfile.lock
>  * pod deintegrate
>  * pod setup
>  * pod install
> ```
> 
> it worked.
> 
> I would recommend of course that you clean the derivedData folder as well.

After trying various different versions of reanimated when building against RN0.72.4 we were still hitting this issue issue until we removed the line from our Podfile that was modifying the `OTHER_CPLUSPLUSFLAGS` setting

After we removed that line and then did just a `rm podfile.lock` and `pod install` our project would compile again - thanks so much @salah-ghanim

**Comment by MaiconLeffa** [comment]
> > The problem in our case was that our project's Podfile included a post_install script that removed all C++ flags (must have been needed for a specific RN version).
> > once removed
> > `config.build_settings['OTHER_CPLUSPLUSFLAGS'] = ''`
> > and the project is cleaned:
> > ```
> >  * rm -rf Pods/*
> >  * rm Podfile.lock
> >  * pod deintegrate
> >  * pod setup
> >  * pod install
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it worked.
> > I would recommend of course that you clean the derivedData folder as well.
> 
> After trying various different versions of reanimated when building against RN0.72.4 we were still hitting this issue issue until we removed the line from our Podfile that was modifying the `OTHER_CPLUSPLUSFLAGS` setting
> 
> After we removed that line and then did just a `rm podfile.lock` and `pod install` our project would compile again - thanks so much @salah-ghanim

Where can I find this line? config.build_settings['OTHER_CPLUSPLUSFLAGS']

**Comment by julianD77** [comment]
The project you are working on might not be making any changes to that setting, but if it does it would be in the CocoaPods Podfile - which usually is located at `ios/Podfile`
