### ISSUE TITLE
TypeError: _ReanimatedModule.default.configureProps is not a function

### ISSUE THREAD

**Issue by nialldbarber** [software-mansion/react-native-reanimated#3333]
## Description
- Started this [as a discussion](https://github.com/software-mansion/react-native-reanimated/discussions/3309) but got no hits and it could be bug (certainly something I can't figure out). 
- I am in the process of updating our app, updating Reanimated from `1.9.0` to `2.8.0`, which also includes various updates to React Native `0.67`, React Navigation 6 etc, so there could be issues there. 
- Every time I try to build the project, I encounter this error:

```
TypeError: _ReanimatedModule.default.configureProps is not a function
```

![Simulator Screen Shot - iPhone 13 - 2022-06-27 at 15 29 43](https://user-images.githubusercontent.com/20539827/176252257-72af4c9c-cffd-4853-a184-e3eb225694a1.png)

- The file in question looks to be in `NavigationOptions.js`, which for reference looks like:

```jsx
export const navigationOptions = (options: Object): Object => ({
  navigation,
}: {
  navigation: NavigationStateType,
}) => ({
  ...options,
})

export const navigationOptionsWithTitle = (options: Object): Object => {
  const initialObject = { ...options }

  return ({ route }: {route: NavigationRouteType}) => ({
    ...initialObject,
    ...titleOptions,
    title: route?.params?.title || options?.title || ''
  })
}

export const navigationOptionsWithDrawer = (options: Object): Object => ({
  navigation,
}: {
  navigation: NavigationStateType,
}) => ({
  headerRight: () => <DrawerButton navigation={navigation} />,
  ...options,
})

export const navigationOptionsWithComponentTitle = (options: Object): Object => ({
  navigation,
}: {
  navigation: NavigationStateType,
}) => ({
  headerTitle: () => <NavigationHeaderTitle navigation={navigation} />,
  ...options,
})
```

### Expected behaviour
- Updating Reanimated should ideally not cause any errors. 

### Actual behaviour & steps to reproduce
- This is a tough one as I'm not able to reproduce it. If someone has seen a similar issue then that would be helpful. 
- I'm thinking there could be some issue with our configuration of React Navigation, which for some reason isn't working on Reanimated v2. 

## Snack or minimal code example
- Unable to replicate this in a snack repo :(((( 

## Package versions
| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         | `0.67.4` |
| react-native-reanimated              | `2.8.0` |
| NodeJS                               | `14.17.6` |
| Xcode                                | `13.3` |
| Java                                 | `11.0.11` |
| Gradle                               | `7.4.2` |

## Affected platforms
- [x] Android
- [x] iOS
- [ ] Web

**Comment by harish-narra** [comment]
ERROR  TypeError: _ReanimatedModule.default.configureProps is not a function. (In '_ReanimatedModule.default.configureProps(Object.keys(NATIVE_THREAD_PROPS_WHITELIST), Object.keys(UI_THREAD_PROPS_WHITELIST))', '_ReanimatedModule.default.configureProps' is undefined)

any fix?

**Comment by nialldbarber** [comment]
> ERROR TypeError: _ReanimatedModule.default.configureProps is not a function. (In '_ReanimatedModule.default.configureProps(Object.keys(NATIVE_THREAD_PROPS_WHITELIST), Object.keys(UI_THREAD_PROPS_WHITELIST))', '_ReanimatedModule.default.configureProps' is undefined)
> 
> any fix?

I haven't found one. Maybe if you also commented with your package versions as well that might be of some use? Though as I can't provide a reproducible repo, I suspect it might be hard to debug.

**Comment by piaskowyk** [comment]
Hey @nialldbarber, Do you sure that you pass all installation steps after updating to Reanimatedc 2? https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation Remember also about clearing the cache after the update - `yarn start --reset-cache `

**Comment by harish-narra** [comment]
Yes still getting same issue

ERROR  TypeError: _ReanimatedModule.default.configureProps is not a function. (In '_ReanimatedModule.default.configureProps(Object.keys(NATIVE_THREAD_PROPS_WHITELIST), Object.keys(UI_THREAD_PROPS_WHITELIST))', '_ReanimatedModule.default.configureProps' is undefined)

**Comment by nialldbarber** [comment]
@piaskowyk I appreciate the response! 

I've made sure to follow the setup for Reanimated 2, including all the extra steps regarding `babel.config.js`. 

I've also tried resetting cache and multiple other things that wipe the slate clean, but neither work and still result in this error.

**Comment by b8ne** [comment]
@nialldbarber I just came across this error when upgrading to v2 too.  I found that another 3rd party package that I was using was strictly looking for react-native-reanimated v1 still, and therefore throwing the error.  
I did a quick cmd+f on my node_modules folder for `"react-native-reanimated": "^1` and found the package.  Saw that I could upgrade the package to a newer version that uses rnr v2, and now all is working.

**Comment by wodin** [comment]
Another way to look for things like that would be to run `npm why react-native-reanimated`

**Comment by piaskowyk** [comment]
The good news, I can reproduce this issue and I know why this happens. I will fix it and describe the source of the problem.

**Comment by desenvolvimento02jocc** [comment]
Having this issue rn, just did an expo upgrade to sdk 46, updated/fixed dependencies and started without cache.

**Comment by piaskowyk** [comment]
@nialldbarber could you run `npm why react-native-reanimated` in your project and send to me the results?

**Comment by FashMuyhee** [comment]
I am also facing this issue

`react-native-reanimated@2.8.0
node_modules/react-native-reanimated
  react-native-reanimated@"2.8.0" from the root project
  peer react-native-reanimated@">=2.2.0" from react-native-circular-progress-indicator@4.4.0
  node_modules/react-native-circular-progress-indicator
    react-native-circular-progress-indicator@"^4.4.0" from the root project
  peer react-native-reanimated@">=2.0.0" from react-native-redash@18.0.0
  node_modules/react-native-redash
    react-native-redash@"*" from react-native-circular-progress-indicator@4.4.0
    node_modules/react-native-circular-progress-indicator
      react-native-circular-progress-indicator@"^4.4.0" from the root project
  peer react-native-reanimated@">=2.2.0" from @gorhom/bottom-sheet@4.4.3
  node_modules/@gorhom/bottom-sheet
    @gorhom/bottom-sheet@"^4.4.3" from the root project
  peer react-native-reanimated@">= 1.0.0" from @react-navigation/drawer@6.4.3
  node_modules/@react-navigation/drawer
    @react-navigation/drawer@"^6.4.3" from the root project
  peer react-native-reanimated@">=2.0.0" from react-native-redash@16.3.0
  node_modules/@gorhom/bottom-sheet/node_modules/react-native-redash
    react-native-redash@"^16.1.1" from @gorhom/bottom-sheet@4.4.3
    node_modules/@gorhom/bottom-sheet
      @gorhom/bottom-sheet@"^4.4.3" from the root project

react-native-reanimated@2.3.1
node_modules/rn-segmented-control/node_modules/react-native-reanimated
  react-native-reanimated@"2.3.1" from rn-segmented-control@1.1.2
  node_modules/rn-segmented-control
    rn-segmented-control@"^1.1.2" from the root project`

after running `npm why react-native-reanimated`

**Comment by piaskowyk** [comment]
@FashMuyhee, could you also show me your exception message?

**Comment by nialldbarber** [comment]
@piaskowyk 
Yep sure thing: 

```
react-native-reanimated@1.13.4
node_modules/react-native-reanimated
  react-native-reanimated@"1.13.4" from the root project
  react-native-reanimated@"^1.4.0" from react-native-ticker@3.2.0
  node_modules/react-native-ticker
    react-native-ticker@"3.2.0" from the root project
```

There are a few packages that definitely need some updating! 😄

**Comment by mberatsanli** [comment]
I got this error too, I adjusted the resolutions in package.json, and it worked for me
https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

```
  "resolutions": {
    "react-native-reanimated": "^2.9.1"
  },
```

**Comment by piaskowyk** [comment]
I described the source of problem and solution in this PR - https://github.com/software-mansion/react-native-reanimated/pull/3441

**Comment by danishiftikhar3** [comment]
> I got this error too, I adjusted the resolutions in package.json, and it worked for me https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/
> 
> ```
>   "resolutions": {
>     "react-native-reanimated": "^2.9.1"
>   },
> ```

THIS WORKED FOR ME!!

THANK YOU!!!

**Comment by mikeRChambers610** [comment]
> > I got this error too, I adjusted the resolutions in package.json, and it worked for me https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/
> > ```
> >   "resolutions": {
> >     "react-native-reanimated": "^2.9.1"
> >   },
> > ```
> 
> THIS WORKED FOR ME!!
> 
> THANK YOU!!!

Hmm... I have same issue but this isn't working for me in SDK 45 expo.

**Comment by wodin** [comment]
@mikeRChambers610 Try removing the resolution and then run `expo-cli doctor` to see if there are any complaints.

**Comment by conorstrejcek** [comment]
@mikeRChambers610 I'm running into the same problem on Expo SDK 45 -- were you able to find a resolution for this?

**Comment by conorstrejcek** [comment]
@mikeRChambers610 I figured out what was going in my case. 

I am using the `expo-updates` package in my project, and as a part of that, there is a property called `runtimeVersion` in the app config. This didn't get incremented automatically with the upgrade process, and was still set to `exposdk:44.0.0`. As a side effect, I was also getting unsymbolicated stack traces from expo go, which made tracking down issues even more challenging. Setting this property to `exposdk:45.0.0` fixed this, and several other issues I was running into as a part of the upgrade process.

You can also set the `runtimeVersion` to be set automatically using a policy:

```ts
runtimeVersion: {
  policy: 'sdkVersion'
}
```

You can check the documentation for this [here](https://docs.expo.dev/eas-update/runtime-versions/) for more details.

**Comment by mikeRChambers610** [comment]
@conorstrejcek thanks for the details! I ended up upgrading my react navigation version from 4 to 6 (which was a bit of a nightmare until I worked it all out) and now I don’t have the issue.

**Comment by samihabuawadSL** [comment]
> I got this error too, I adjusted the resolutions in package.json, and it worked for me https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/
> 
> ```
>   "resolutions": {
>     "react-native-reanimated": "^2.9.1"
>   },
> ```
Thx
worked for me after removing the package and installing again

**Comment by nishadadilshan** [comment]
I'm facing  with this type of error.  ERROR - **n.default.configureProps is not a function.** 
"react": "18.2.0", "react-native": "0.69.1".

**Comment by Yandamuri** [comment]
@nishadadilshan Did you find any solution?

**Comment by harish-narra** [comment]
use the below code in the package.json file 

"resolutions": {
    "react-native-reanimated": "1.13.3"
  },
    "dependencies": {
    "react-native-reanimated": "1.13.3"
}

**Comment by Yandamuri** [comment]
Thank you su much for your response. May I know what "resolutions" block does?

**Comment by nandorojo** [comment]
`resolutions` overrides any of your package versions across your node modules/package.json files to enforce a certain version.

**Comment by huseyinekh** [comment]
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      // Required for expo-router
      'expo-router/babel',
      'react-native-reanimated/plugin'
    ],
  };
};
// npx expo install expo-router react-native-safe-area-context react-native-screens expo-linking expo-constants expo-status-bar react-native-gesture-handler

**Comment by welschmoor** [comment]
Same problem, nothing works, _ReanimatedModule.default.createNode is not a function

**Comment by innocodes** [comment]
> Same problem, nothing works, _ReanimatedModule.default.createNode is not a function

I am facing this error too, as of today.
