### PR TITLE
Move `REANIMATED_VERSION` definition to ReanimatedVersion.h

### PR DESCRIPTION
**Pull request by tomekzaw**
## Summary

This PR eliminates code duplication introduced in #3810.

## Test plan

Just run Example and FabricExample apps on Android and iOS.

### CODE REVIEW

**Review by piaskowyk — APPROVED** [review]

**Comment by DanielRiera** [comment]
xCode fail with this error Use of undeclared identifier 'REANIMATED_VERSION_STRING'

**Comment by tomekzaw** [comment]
@DanielRiera Can you please submit an issue and specify React Native version etc.?

**Comment by DanielRiera** [comment]
#4009 Here :)
