### ISSUE TITLE
scrollTo is not a function

### ISSUE THREAD

**Issue by kagod-dev** [software-mansion/react-native-reanimated#8361]
### Description

I get an error on web that `scrollTo` is not a function after bumping to 3.19.2.

IMHO this is due to incorrect [cherry-pick](https://github.com/software-mansion/react-native-reanimated/pull/8334/files#diff-a98b820e995e73c1ce7fe27c3ad58e503b5361258bea29c41eafdcb95fdf1a09) applied to version 3.19.
Original [fix](https://github.com/software-mansion/react-native-reanimated/pull/8327/files#diff-a98b820e995e73c1ce7fe27c3ad58e503b5361258bea29c41eafdcb95fdf1a09) changed the if condition and in if body logged a warning and returned. But the [cherry-pick ](https://github.com/software-mansion/react-native-reanimated/pull/8334/files#diff-a98b820e995e73c1ce7fe27c3ad58e503b5361258bea29c41eafdcb95fdf1a09) changed the if body without changing the condition. That leads to calling `scrollTo` on uninitialized element.
After reverting that patch locally it works fine.

### Steps to reproduce

1. Run the [scrollTo](https://docs.swmansion.com/react-native-reanimated/docs/scroll/scrollTo/) example with 3.19.2 version

### Snack or a link to a repository

https://snack.expo.dev/@kagod-dev/scrollto-reanimated-3-19-2

### Reanimated version

3.19.2

### Worklets version

0.6.0

### React Native version

0.78.3

### Platforms

Web

### JavaScript runtime

Hermes

### Workflow

React Native CLI

### Architecture

New Architecture (Fabric renderer)

### Host machine

None

### Acknowledgements

Yes

**Comment by MatiPl01** [comment]
Hey @kagod-dev!

Thanks for reporting the issue. I must have made this stupid mistake and forgot to update the `if` condition to the correct one. I will prepare a quick fix and I think we can publish `3.19.3` right after it is merged.

**Comment by MatiPl01** [comment]
Hey @kagod-dev! I have just released `3.19.3` with a fix for this issue. Can you please upgrade reanimated and check if the issue is now fixed?

**Comment by MatiPl01** [comment]
I am closing the issue as it should be fixed in the Reanimated `3.19.3`. If the problem still persists, please reopen the issue.
