### ISSUE TITLE
jestUtils not resolved with 2.4.0

### ISSUE THREAD

**Issue by Andarius** [software-mansion/react-native-reanimated#2949]
## Description

`require('react-native-reanimated/lib/reanimated2/jestUtils').setUpTests()` fails with 
```
    Cannot find module 'react-native-reanimated/lib/reanimated2/jestUtils' from '__tests__/setup.ts'

      1 | import '@testing-library/jest-native/extend-expect'
      2 | // import { printExpected } from 'jest-matcher-utils'
    > 3 | require('react-native-reanimated/lib/reanimated2/jestUtils').setUpTests()
        | ^
      4 |

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (__tests__/setup.ts:3:1)
```

It seems that the new path is `react-native-reanimated/lib/src/reanimated2/jestUtils` but after changing the path I get the following error:

```
Cannot find module 'react-native-reanimated' from 'app/hooks/useOnScroll.ts'

      3 |     NativeScrollEvent, NativeSyntheticEvent
      4 | } from 'react-native'
    > 5 | import Animated, { useAnimatedScrollHandler, useSharedValue } from 'react-native-reanimated'
        | ^
      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (app/hooks/useOnScroll.ts:5:1)
```

### Expected behavior

Should not fail

### Actual behavior & steps to reproduce

Install `2.4.0`

## Snack or minimal code example

`require('react-native-reanimated/lib/reanimated2/jestUtils').setUpTests()`

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native-reanimated              |  2.4.0       |

**Comment by rodperottoni** [comment]
Yep, can repro this 10/10 times. 

The second issue (`Cannot find module 'react-native-reanimated' from 'app/hooks/useOnScroll.ts'`) seems to be caused by #2954. Changing the `main` value (in `node_modules/react-native-reanimated/package.json`) to `lib/src/Animated.js` seems to fix the issue for me.

**Comment by alaintalk** [comment]
i have the same issue

**Comment by MuhmdRaouf** [comment]
you can just change the import for the following:

`require('react-native-reanimated/src/reanimated2/jestUtils').setUpTests();`

till they fixed it in the next release then revert it back to the old import.

**Comment by MuhmdRaouf** [comment]
you can just change the import for the following:

`require('react-native-reanimated/lib/src/reanimated2/jestUtils').setUpTests();`

till they fixed it in the next release then revert it back to the old import.
