### ISSUE TITLE
Reanimated Crashes in Expo SDK 51.0.11 | "TypeError: animatedRef.getTag is not a function (it is undefined)"

### ISSUE THREAD

**Issue by chadders404** [software-mansion/react-native-reanimated#6113]
### Description

Since upgrading to SDK 51.0.11, my apps using Reanimated crash. Below is the error:

` TypeError: animatedRef.getTag is not a function (it is undefined)`

Source of the error is indicated to be in useScrollViewOffset.ts line 105:9:

```
  if (scrollRefTag === null) {
      console.warn(
        '[Reanimated] ScrollViewOffset failed to resolve the view tag from animated ref. Did you forget to attach the ref to a component?'
      );
    } else {
      eventHandler.workletEventHandler.registerForEvents(scrollRefTag.current);
    }
```

I am running SDK 51.0.11 and Reanimated ~3.10.1. The apps were working fine in Expo SDK 50.0.14. 

As this has happened on a couple of apps and is reproducable in a snack, I'm enclined to say this is an issue with Reanimated or the SDK.

### Steps to reproduce

1. Be using Expo SDK 51 and Reanimated ~3.10.1
2. Import useScrollViewOffset and useAnimatedRef from react native reanimated

### Snack or a link to a repository

https://snack.expo.dev/@chadders404/reanimated-crash-expo-sdk-51

### Reanimated version

~3.10.1

### React Native version

0.74.2

### Platforms

iOS

### JavaScript runtime

None

### Workflow

Expo Go

### Architecture

None

### Build type

None

### Device

Real device

### Device model

iPhone 11 Pro

### Acknowledgements

Yes

**Comment by szydlovsky** [comment]
Hey @chadders404, yeah there were some design issues with the code of `useScrollViewOffset`. It should be fixed in ^3.12 versions though - let me know if it helps!

**Comment by szydlovsky** [comment]
@oddanderson I suggest that you create a development build instead. It lets you install any native libraries you want (so, bumping the Reanimated as well). More info on development builds can be found here: https://docs.expo.dev/develop/development-builds/introduction/

**Comment by MULERx** [comment]
this error occurs in the react-native-reanimated v3.10.1 so, this error will fix if you upgrade your react-native-reanimated to the latest v3.13.0

**Comment by MULERx** [comment]
for now expo 51 not compatible with Reanimated  3.12 or more, but the above error is fixed this way

```
 // Initialize hooks at the top level
const scrollRef = useAnimatedRef<Animated.ScrollView>();
  const scrollOffset = useSharedValue(0);

  const scrollHandler = useAnimatedScrollHandler(event => {
    scrollOffset.value = event.contentOffset.y;
  });
  
  <Animated.ScrollView
        ref={scrollRef}
        onScroll={scrollHandler} > 
        .................................
   </Animated.ScrollView>    
   
   ```

**Comment by prescarlton** [comment]
@MULERx 
using Expo 52, this fixed it for me as well. Thank you!
