### ISSUE TITLE
useScrollViewOffset getting -> animatedRe.getTag is not a function (it is undefined)

### ISSUE THREAD

**Issue by Eramirez06** [software-mansion/react-native-reanimated#7170]
### Description

The method useScrollViewOffset is not working on version 3.17.1
using 
"react": "19.0.0",
"react-native": "0.78.0",
"react-native-gesture-handler": "^2.24.0"

please note the rest of the reanimated it's working fine only this method

### Steps to reproduce

do that and it's failing

import { useScrollViewOffset } from 'react-native-reanimated';

function App() {
  const animatedRef = useAnimatedRef();
  const scrollOffset = useScrollViewOffset(animatedRef);
  return (
    <Animated.ScrollView ref={animatedRef}>{/* ... */}</Animated.ScrollView>
  );
}

### Snack or a link to a repository

https://snack.expo.dev/@eramirez/usescrollviewoffset-crash

### Reanimated version

3.7.1

### React Native version

0.78.0

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Device model

Iphone 16 pro max

### Acknowledgements

Yes

**Comment by MatiPl01** [comment]
You are using Reanimated `3.17.1`, not `3.7.1` which you specified under the **Reanimated version** section, right?

For me everything works fine (in Reanimated example app, on a clean project and in my personal project that uses `useScrollViewOffset`; your example also works fine).

Have you recently bumped all dependencies on an existing project? If you did, this might be related to the invalid repo state that many people are experiencing after the last RN/React update. Would you be able to share a repository or prepare a small reproduction repository where you are getting this error?

Could you also tell me if you are using a monorepo in your project?
