### ISSUE TITLE
reanimated@4.1_70f5e8f27bf7ac0cf82a8de0d907e445/node_modules/react-native-reanimated/lib/typescript/Animated"' has no exported member 'EasingFunction'.

### ISSUE THREAD

**Issue by MOHAMED-LAAGUILI** [software-mansion/react-native-reanimated#8434]
### Description

after i updated expo from 53 to 54 i get this error  in the reanimated
 ```
tsc  --noemit

node_modules/.pnpm/@gorhom+bottom-sheet@5.2.6__5871f0aeba8052e2cbf0d527f39609de/node_modules/@gorhom/bottom-sheet/src/constants.ts:72:34 - error TS2694: Namespace '"C:/Users/LAAGUILI MOHAMED/Downloads/TimeTracker/node_modules/.pnpm/react-native-reanimated@4.1_70f5e8f27bf7ac0cf82a8de0d907e445/node_modules/react-native-reanimated/lib/typescript/Animated"' has no exported member 'EasingFunction'.

72 const ANIMATION_EASING: Animated.EasingFunction = Easing.out(Easing.exp);
                                    ~~~~~~~~~~~~~~

tsconfig.json:41:27 - error TS5024: Compiler option 'include' requires a value of type string.

41     "nativewind-env.d.ts",
  


Found 2 errors in 2 files.

Errors  Files
     1  node_modules/.pnpm/@gorhom+bottom-sheet@5.2.6__5871f0aeba8052e2cbf0d527f39609de/node_modules/@gorhom/bottom-sheet/src/constants.ts:72
     1  tsconfig.json:41
 ELIFECYCLE  Command failed with exit code 2.
PS C:\Users\LAAGUILI MOHAMED\Downloads\TimeTracker> 
```

### Steps to reproduce

none

### Snack or a link to a repository

none

### Reanimated version

~4.16.0

### Worklets version

0.5.1

### React Native version

0.81.4

### Platforms

Web, Android, iOS

### JavaScript runtime

Hermes

### Workflow

Expo Dev Client

### Architecture

New Architecture (Fabric renderer)

### Host machine

Windows

### Acknowledgements

No

**Comment by MOHAMED-LAAGUILI** [comment]
the repo is private

**Comment by Maroka745** [comment]
Waving Hand Emoji Hello, I'm Mohamed's Avatar Mohamed! Profile views counter
I’m a Full Stack Software Developer 🚀 from Morocco 🇲🇦 with a passion for building web and mobile applications. I love solving complex challenges through creative solutions and have a growing curiosity about artificial intelligence. Let’s build something amazing together! 💡

🚀 About Me

Professional Animation Coder

💻 Skilled in Full Stack Development.
🎓 Constant learner, I'm up Mobile Development to build amazing cross-platform mobile apps.
🛠️ Passionate about crafting sleek, scalable side projects and contributing to open-source initiatives.
💬 Ask me about React/Next/ReactNative, Laravel, PostgreSQL/MySQL, Bootstrap/Tailwind Css, or anything web-related!
🛠️ Tech Stack

HTML5  CSS3  Sass  SCSS  Bootstrap Tailwind CSS  NativeWind  jQuery  Git GitFlow  JavaScript  TypeScript  React React Native  Next.js  PHP  Laravel MySQL  PostgreSQL  SQL  Firebase MongoDB
🌟 What I’m Working On

🧑‍💻 Writing clean, maintainable code with a focus on UI/UX excellence and leveraging Domain-Driven Design (DDD) to solve complex business problems.
🚀 Advancing my skills in the Laravel & React stack, using best practices and industry standards to build scalable and maintainable systems.
📲 Exploring cross-platform mobile development for iOS and Android, integrating modern frameworks and techniques.
📈 Continuously sharpening my technical and interpersonal skills, embracing agile methodologies, test-driven development (TDD), and industry best practices.
💼 With over 5 years of professional development experience, I pride myself on architecting robust, scalable applications and working with teams to deliver high-quality, performant software solutions.
🤝 Let’s Collaborate

I’m always open to working on innovative projects that push tech boundaries! If you have an exciting idea or need an extra hand, let’s connect and bring it to life.

✉️ Connect With Me

 Gmail  LinkedIn  Portfolio Discord  WhatsApp Buy Me a Coffee

**Comment by Maroka745** [comment]
A React + Next Js full stack ecomerce website that has an integration of that new tech of Clerk that do instance of Auth controls and an integration of ease CMS manupilation and controls of the sanity stripe payment compatible to dark theme seamless scalabale ui with auth user and admin session stripe payment

live demo https://react-next-clerk-sanity-ecommerce-767896446.vercel.app/ react-next-clerk-sanity-ecommerce-767896446 vercel app

**Comment by Maroka745** [comment]
React + Vite
weather app a simple as that image

**Comment by MatiPl01** [comment]
Hey @MOHAMED-LAAGUILI!

Are you sure that this issue is caused by reanimated? The error that you pasted in the issue description seems to show that there is a problem with the `@gorhom/bottom-sheet` library which tries to get the `EasingFunction` type from the `Animated` namespace exported from reanimated but reanimated doesn't export this type via the `Animated` namespace.

In general, you should never typecheck libraries as they might be type issues in their sources and this is fine as long as there are no runtime issues. I'd suggest changing your tsconfig (set the [skipLibCheck](https://www.typescriptlang.org/tsconfig/#skipLibCheck) option to `true`).

If it doesn't work, please patch the `@gorhom/bottom-sheet` library and change the problematic type to the `EasingFunction` type imported directly from the `'react-native-reanimated'` instead of trying to get the type from the `Animated` namespace:

```ts
import type { EasingFunction } from 'react-native-reanimated';

...

const ANIMATION_EASING: EasingFunction = Easing.out(Easing.exp);
```

**Comment by tomekzaw** [comment]
Also, make sure you're importing `Easing` from `react-native-reanimated` and not the one from `react-native`.

**Comment by MatiPl01** [comment]
@tomekzaw This type error is thrown in the gorhom's bottom sheet library in [this](https://github.com/gorhom/react-native-bottom-sheet/blob/d12f3f7da19e5152fb541c4cfd36340cf5274473/src/constants.ts#L3) file. It imports the `Easing` object properly from the `react-native-reanimated`. There's just an issue with the `EasingFunction` type.

**Comment by MOHAMED-LAAGUILI** [comment]
yeah it was graham problem 
I had suppressed that ts lint error 
thanks all
ill clos ticket for now
