### ISSUE TITLE
ld: symbol(s) not found for architecture arm64 clang++: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by stickor** [software-mansion/react-native-reanimated#6871]
### Description

react native 0.76.5
xcode 16.2 
macos

<img width="1056" alt="image" src="https://github.com/user-attachments/assets/deb7ca05-f913-4018-ba07-ca694ad9d38c" />

### Steps to reproduce

npm i react-native-reanimated
cd ios && pod install && cd ..
build in xcode 16.2 then error
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/f3674920-d684-45e4-8b6b-05639ed978ca" />

### Snack or a link to a repository

none

### Reanimated version

3.16.6

### React Native version

0.76.5

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by stickor** [comment]
RNReanimated.podspec  add  `s.static_framework = true`
it work for me

**Comment by Jatin-Rane-007** [comment]
> RNReanimated.podspec add `s.static_framework = true` it work for me

is it gets fixed after adding s.static_framework = true? is there no other way to fix?
