### ISSUE TITLE
TypeError: require.resolveWeak is not a function

### ISSUE THREAD

**Issue by santhosh-umapathi-wikifolio** [software-mansion/react-native-reanimated#7891]
### Description

Hi,

After upgrading to latest version, now the jest tests started to fail with the error `TypeError: require.resolveWeak is not a function`

We are using `jest.setup.ts`
```
// Mock for react-native-reanimated
      2 | jest.mock('react-native-reanimated', () =>
    > 3 |   require('react-native-reanimated/mock'),
        |   ^
      4 | );
```

### Steps to reproduce

`npx jest --watch`

### Snack or a link to a repository

-

### Reanimated version

4.0.0

### React Native version

0.80.1

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

Fabric (New Architecture)

### Host machine

None

### Acknowledgements

Yes

**Comment by santhosh-umapathi-wikifolio** [comment]
After adding 2 global mock files, issue was resolved

`__mocks__/react-native-reanimated.ts`:
```
// Mock - for react-native-reanimated v4.0.0
const NOOP = () => {
  /* empty function */
};
const IDENTITY = (x: any) => x;

// Create mock Animated components
const mockAnimated = (component: string) => component;

// Mock basic Reanimated functionality
const Reanimated = {
  // Core
  useSharedValue: (initialValue: any) => ({
    value: initialValue,
    set: jest.fn(value => {
      if (typeof value === 'function') {
        initialValue = value();
      } else {
        initialValue = value;
      }
      return initialValue;
    }),
    get: jest.fn(() => initialValue),
  }),
  useDerivedValue: (processor: any) => ({
    value: typeof processor === 'function' ? processor() : null,
  }),
  useAnimatedStyle: () => ({}),
  useAnimatedProps: () => ({}),
  useAnimatedGestureHandler: () => ({}),
  useAnimatedReaction: NOOP,
  useAnimatedRef: () => ({current: null}),
  useAnimatedScrollHandler: () => NOOP,

  // Animations
  withTiming: (toValue: any) => toValue,
  withSpring: (toValue: any) => toValue,
  withDecay: (toValue: any) => toValue,
  withDelay: (_: any, animation: any) => animation,
  withSequence: (..._: any[]) => 0,
  withRepeat: (..._: any[]) => 0,
  cancelAnimation: NOOP,

  // Layout animations
  Layout: {
    springify: NOOP,
    duration: NOOP,
    damping: NOOP,
    mass: NOOP,
    stiffness: NOOP,
    overshootClamping: NOOP,
    restDisplacementThreshold: NOOP,
    restSpeedThreshold: NOOP,
    easing: NOOP,
  },

  // Constants and utilities
  Easing: {
    linear: IDENTITY,
    ease: IDENTITY,
    quad: IDENTITY,
    cubic: IDENTITY,
    poly: () => IDENTITY,
    sin: IDENTITY,
    circle: IDENTITY,
    exp: IDENTITY,
    elastic: () => IDENTITY,
    back: () => IDENTITY,
    bounce: () => IDENTITY,
    bezier: () => IDENTITY,
    in: () => IDENTITY,
    out: () => IDENTITY,
    inOut: () => IDENTITY,
  },

  // Test utilities
  setUpTests: jest.fn(),

  // Exports for components
  View: mockAnimated('View'),
  Text: mockAnimated('Text'),
  Image: mockAnimated('Image'),
  ScrollView: mockAnimated('ScrollView'),
  FlatList: mockAnimated('FlatList'),

  // V4 specific APIs
  runOnJS: (fn: Function) => fn,
  runOnUI: (fn: Function) => fn,

  // Hooks for scroll
  useScrollViewOffset: () => ({value: 0}),
  useAnimatedKeyboard: () => ({height: {value: 0}}),

  // Utilities
  interpolate: IDENTITY,
  interpolateColor: () => '#000000',
  createAnimatableComponent: IDENTITY,

  // Animation modifiers
  withStyleAnimation: () => ({}),

  // Entry-point mocks
  createWorklet: (fn: any) => fn,

  // Gesture handlers
  Gesture: {
    Tap: () => ({
      onStart: () => ({}),
      onEnd: () => ({}),
      enabled: () => ({}),
    }),
    Pan: () => ({
      onStart: () => ({}),
      onUpdate: () => ({}),
      onEnd: () => ({}),
      enabled: () => ({}),
    }),
    Pinch: () => ({
      onStart: () => ({}),
      onUpdate: () => ({}),
      onEnd: () => ({}),
      enabled: () => ({}),
    }),
    Rotation: () => ({
      onStart: () => ({}),
      onUpdate: () => ({}),
      onEnd: () => ({}),
      enabled: () => ({}),
    }),
    Fling: () => ({
      onStart: () => ({}),
      onEnd: () => ({}),
      enabled: () => ({}),
    }),
    LongPress: () => ({
      onStart: () => ({}),
      onEnd: () => ({}),
      enabled: () => ({}),
    }),
  },

  // Re-export from worklet
  makeMutable: (val: any) => ({value: val}),

  // Math functions
  abs: Math.abs,
  acos: Math.acos,
  asin: Math.asin,
  atan: Math.atan,
  atan2: Math.atan2,
  ceil: Math.ceil,
  cos: Math.cos,
  exp: Math.exp,
  floor: Math.floor,
  log: Math.log,
  max: Math.max,
  min: Math.min,
  pow: Math.pow,
  round: Math.round,
  sin: Math.sin,
  sqrt: Math.sqrt,
  tan: Math.tan,

  // Mockable for testing
  __reanimatedWorkletInit: jest.fn(),
};

// Mock for default export
module.exports = Reanimated;
```

`__mocks__/react-native-worklets.ts`:
```
// Mock -  for react-native-worklets
const Reanimated = require('react-native-reanimated');
// Use the same implementations as in our reanimated mock
const runOnJS = Reanimated.runOnJS;
const runOnUI = Reanimated.runOnUI;

module.exports = {
  runOnJS,
  runOnUI,
};
```

**Comment by RohovDmytro** [comment]
I also have to add that this issue (I assume) breaks expo web. During developing on a web version, I see this warning:

WARNING in ./node_modules/react-native-worklets/lib/module/initializers.js 129:22-29
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
Built in 707ms

And if I try to export the web-js the error happens.

**Comment by tjzel** [comment]
Thanks for reporting this issue. Unfortunately, it doesn't reproduce on our end - could somebody add a repro?

**Comment by amruthskanda** [comment]
+1

@tjzel  Reproduces for me as well. Mine is a complex app to share repro. But facing the exact same issue as in description after upgrading to 4.0.0 in my existing project that uses RN 0.76.7 and jest 29.7.0 with exactly similar mock setup using setup-jest.js.

**Comment by santhosh-umapathi-wikifolio** [comment]
@tjzel , Mine is a complex setup to share the repro as well. Could it be the reason due to the `react-native-worklets` mock setup?

**Comment by tjzel** [comment]
I don't know. It's next to impossible to troubleshoot such an issue without any kind of reproduction.

**Comment by oleksandr-dziuban** [comment]
Hey guys

Just add this line in setupTests jest file:

```
globalThis._WORKLETS_BUNDLE_MODE = false;
```

**Comment by Ralexs0096** [comment]
+1, same issue. 

RN version: 0.80.0
"react-native-reanimated": "^4.0.2",
"react-native-worklets": "^0.4.1"

```js
  TypeError: require.resolveWeak is not a function

      16 | } from 'react-native-gesture-handler';
    > 17 | import { runOnJS } from 'react-native-worklets';
```

**Comment by H3manth31** [comment]
+1, facing the same issue.

For now though @santhosh-umapathi-wikifolio manual mock worked.

**Comment by mlecoq** [comment]
replacing 

```
jest.mock('react-native-reanimated', () =>
  require('react-native-reanimated/mock'),
);
```

with 


```
const AnimatedMock = require('react-native-reanimated/mock');
jest.mock('react-native-reanimated', () => AnimatedMock);
```

fixed the issue for me

**Comment by tjzel** [comment]
The fix for this issue will be released in react-native-worklets@0.5.1 tonight.
