### PR TITLE
Add react-native-v8 support

### PR DESCRIPTION
**Pull request by Kudo**
## Description

Add react-native-v8 support. Fixes #1897

## Changes

- modify `FOR_HERMES: boolean` to `JS_RUNTIME = "hermes" | "jsc" | "v8"` in build scripts.
- in android `NativeProxy.cpp`, will have `JS_RUNTIME_HERMES=1`, `JS_RUNTIME_V8=1` or `JS_RUNTIME_JSC=1` to make preprocessor easier to support three different js runtimes.
- to save reanimated published npm package size, this pr does not prebuild aar for v8 support.

## Test code and steps to reproduce

local package built from `createNPMPackage.sh`
- ✅ react-native 0.67 + jsc + prebuilt reanimated aar
- ✅ react-native 0.67 + hermes + prebuilt reanimated aar
- ✅ react-native 0.67 + jsc + building reanimated from source (remove `node_modules/react-native-reanimated/android/*.aar`)
- ✅ react-native 0.67 + hermes + building reanimated from source (remove `node_modules/react-native-reanimated/android/*.aar`)
- ✅ react-native 0.67 + react-native-v8 + building reanimated from source

detailed steps to test v8 projects:

- `npx react-native init TestApp`
- install react-native-v8 from [the steps](https://github.com/Kudo/react-native-v8#installation-for-react-native--066). alternatively, i personally use [this automation script](https://github.com/Kudo/react-native-v8/tree/main/scripts) 😁
- `yarn add file:/path/to/local-build-react-native-reanimated.tgz` (from `createNPMPackage.sh`)
- modify `babel.config.js` for reanimated.
- `yarn android`

let me know if a minimal v8 example is preferred. i can prepare one if needed.

## Checklist

- [ ] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Added TS types tests
- [ ] Added unit / integration tests
- [ ] Updated documentation
- [ ] Ensured that CI passes

### CODE REVIEW

**Comment by jzxchiang1** [comment]
@piaskowyk Sorry to bother, but do you mind taking a look at this? This would be huge for react-native-v8 users!

**Comment by jzxchiang1** [comment]
@Kudo 

Actually, I got an error in this [line](https://github.com/Kudo/react-native-reanimated/blob/e8d105519b41c3e9558207fb600a5e17338ca768/android/build.gradle#L182) when I tried running `./createNPMPackage.sh` in a local clone of your forked repo on the `support-v8` branch:

```
+ ./gradlew clean

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/justinchiang/react-native-reanimated/android/build.gradle' line: 182

* What went wrong:
A problem occurred evaluating root project 'android'.
> Cannot get property 'ext' on null object
```

Where did you run `./createNPMPackage.sh` from? The build.gradle can't seem to find an `appProject` when I run it.

**Comment by Kudo** [comment]
> Actually, I got an error in this [line](https://github.com/Kudo/react-native-reanimated/blob/e8d105519b41c3e9558207fb600a5e17338ca768/android/build.gradle#L182) when I tried running `./createNPMPackage.sh` in a local clone of your forked repo on the `support-v8` branch:

sorry i broke that from the last minute refactoring. it is fixed by the latest commit. thanks for the kindly verification 💯

**Comment by jzxchiang1** [comment]
Thanks, that fixed it!

Unfortunately, there are more errors.

I think you forgot to add "v8" [here](https://github.com/software-mansion/react-native-reanimated/blob/efcf5525720fcca2854bbedb892e2dc2f7c02ae0/createNPMPackage.sh#L15).

However, when I do add it and rerun `./createNPMPackage.sh`, I get an error:

```
BUILD SUCCESSFUL in 1s
4 actionable tasks: 4 executed
+ CLIENT_SIDE_BUILD=False
+ JS_RUNTIME=v8
+ ./gradlew :assembleDebug --no-build-cache --rerun-tasks

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/justinchiang/react-native-reanimated-v8/android/build.gradle' line: 353

* What went wrong:
A problem occurred evaluating root project 'android'.
> Cannot invoke method getProjectDir() on null object
```

This is the offending [line](https://github.com/software-mansion/react-native-reanimated/blob/efcf5525720fcca2854bbedb892e2dc2f7c02ae0/android/build.gradle#L353). I think it's because `react-native-v8` wasn't installed in your react-native-reanimated fork?

Do you also mind sending over a tgz file that you build, e.g. react-native-reanimated-2.5.0.tgz? I'd like to try testing with it while we sort out these build errors. 😀

**Comment by Kudo** [comment]
@jzxchiang1 that's intentional. `createNPMPackage.sh` is for prebuilding aar and publish to npm. so far it's for hermes and jsc only. i don't think it makes sense for reanimated to include prebuilt aars for every js runtimes.
for v8, both react-native-v8 and react-native-reanimated are building from source when you executed the gradle command.

**Comment by jzxchiang1** [comment]
> @jzxchiang1 that's intentional. `createNPMPackage.sh` is for prebuilding aar and publish to npm. so far it's for hermes and jsc only. i don't think it makes sense for reanimated to include prebuilt aars for every js runtimes. for v8, both react-native-v8 and react-native-reanimated are building from source when you executed the gradle command.

Hmm not sure I understand. How do I test this PR then?

I want to build a v8 AAR so I can install a local NPM module for 2.5.0 reanimated. I thought I had to run `./createNPMPackage.sh` to do that. Is there another way?

**Comment by Kudo** [comment]
@jzxchiang1 that's my way to test it:

```sh
$ git clone https://github.com/Kudo/react-native-v8.git
$ cd react-native-v8
$ python scripts/gen_project.py --rn-version 0.68 --npm-source 1.1.1 TestApp
$ cd TestApp
$ yarn add https://github.com/Kudo/react-native-reanimated#support-v8

# edit babel.config.js and App.js

$ yarn android
```

**Comment by jzxchiang1** [comment]
Whoa interesting! Let me give this a try thanks.

**Comment by gpbaculio** [comment]
@Kudo the apk size is 52.4mb by default, pls advice me how to reduce? Thank you

**Comment by Kudo** [comment]
@gpbaculio https://github.com/Kudo/react-native-v8#how-to-reduce-apk-size-
the question is not related to this pr and reanimated. for react-native-v8 questions, please go to react-native-v8 repo.

**Comment by jzxchiang1** [comment]
I was able to get this working on iOS with RN 0.64.2 and @Kudo's branch (which uses reanimated 2.6.0 I believe).

Thank you!

However, I'm not able to build my app on Android. It might be due to the low RN version. Not sure...

The error is:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-reanimated:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/justinchiang/.../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedUIImplementation.java:13: error: cannot find symbol
      ViewManagerResolver viewManagerResolver,
      ^
  symbol:   class ViewManagerResolver
  location: class ReanimatedUIImplementation
/Users/justinchiang/.../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedUIImplementation.java:11: error: recursive constructor invocation
  public ReanimatedUIImplementation(
         ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.
```

**Comment by jzxchiang1** [comment]
I think it's because it's not applying the Java patches correctly: https://github.com/Kudo/react-native-reanimated/blob/efcf5525720fcca2854bbedb892e2dc2f7c02ae0/android/build.gradle#L462

**Comment by jzxchiang1** [comment]
That is one issue, another issue is how libraries with native dependencies like `react-native-vision-camera` should use this v8 reanimated.

Since there's no AAR, does that mean those libraries no longer need to extract JNI and SO files?

For example, this patch that I've been using no longer works because this PR no longer creates a v8 AAR:

https://gist.github.com/jzxchiang1/012af920bca8b335faab2d913fd6293d#file-react-native-vision-camera-2-9-4-patch-L97

How can libraries extract those files?

**Comment by jzxchiang1** [comment]
I thought about this, and I think it's easier if this PR could still create a v8 AAR (like what Hermes and JSC do).

Otherwise, this will cause a lot of headaches for developers using other libraries that natively depend on reanimated. They will be more reluctant to support v8 reanimated.

**Comment by Kudo** [comment]
@jzxchiang1
  - react-native-v8 v1 only supports react-native>=0.66.0. for your case on 0.64, please uses the custom patch and custom prebuilt reanimated + v8 you had.
  - for vision camera, they can extract libreanimated.so not only from AAR but the gradle build output. for example, [we link the libv8executor.so from gradle build output](https://github.com/software-mansion/react-native-reanimated/pull/3132/files#diff-59c313fb0dfe322996885368a5a90d8f8400c2576bb64acc60467c2e79ecd2e9R179-R185).

**Comment by jzxchiang1** [comment]
I am pleased to confirm that this PR works for me after upgrading RN to 0.67.4 and using react-native-v8 1.1.0.

In order to get it working with react-native-vision-camera (I am using 2.11.2), you can patch this:

https://gist.github.com/jzxchiang1/418832d01dcb8a4c01a01c16d8772365

@Kudo's advice was very helpful, and I finally got it to work.

LGTM.

**Comment by jzxchiang1** [comment]
The only issue I've seen during runtime is in Android, where my app will suddenly crash (after interacting with react-native-bottom-sheet, which uses reanimated) with this error:

```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7469636f6c657628
    x0  b400007d0fedad70  x1  0000007ca4cfd338  x2  0000000000000002  x3  0000000000000004
    x4  0000007ca4cfd33a  x5  0000007ca4cfd368  x6  0000000000000001  x7  0000000000000001
    x8  00000000000000b9  x9  1baffed00baffedf  x10 b400007ccff02d70  x11 b400007d0fedad70
    x12 0000000000000001  x13 0000000000000003  x14 000000000004200c  x15 0000000030000000
    x16 0000007c12757dc8  x17 0000007c11e2ea1c  x18 0000007ca0f0c000  x19 7469636f6c657610
    x20 b400007ebfe79040  x21 0000007c127789fc  x22 0000000000000005  x23 0000007ca4d05000
    x24 0000007c13b38e8c  x25 0000007c12778000  x26 0000007b0a646e51  x27 0000007ca4d05000
    x28 b400007ebfe84100  x29 0000007ca4cfd480
    lr  0000007c13b71f54  sp  0000007ca4cfd480  pc  0000007c11e2ea48  pst 00000000a0001000
backtrace:
      #00 pc 0000000000deaa48  /data/app/~~vJSdr9OV4egKJ24_qiga8w==/com.testapp-QsLrKpSyxD4xIiETqAImXQ==/lib/arm64/libv8android.so (v8::internal::GlobalHandles::NodeSpace<v8::internal::GlobalHandles::Node>::Release(v8::internal::GlobalHandles::Node*)+44) (BuildId: d77b0179dd66c987)
      #01 pc 00000000000abf50  /data/app/~~vJSdr9OV4egKJ24_qiga8w==/com.testapp-QsLrKpSyxD4xIiETqAImXQ==/lib/arm64/libv8executor.so (rnv8::V8PointerValue::~V8PointerValue()+104) (BuildId: 4333bd01b6f2f93e121b86fc0b8d8aac4756be49)
      #02 pc 00000000000ac660  /data/app/~~vJSdr9OV4egKJ24_qiga8w==/com.testapp-QsLrKpSyxD4xIiETqAImXQ==/lib/arm64/libv8executor.so (rnv8::V8PointerValue::invalidate()+52) (BuildId: 4333bd01b6f2f93e121b86fc0b8d8aac4756be49)
```

I've seen someone [report](https://github.com/software-mansion/react-native-reanimated/issues/2430) this error but only for 2.2.2. Unfortunately, using this PR with reanimated 2.5.0, I still see this error quite frequently on Android.

Is there possibly some edge case with v8 and reanimated? There seems to be some null pointer dereferencing going on...

**Comment by Kudo** [comment]
@jzxchiang1 could you help to open a new issue to react-native-v8 and create a minimal reproducible example? i'm happy to troubleshoot if i can repro the crash.

**Comment by jzxchiang1** [comment]
> @jzxchiang1 could you help to open a new issue to react-native-v8 and create a minimal reproducible example? i'm happy to troubleshoot if i can repro the crash.

Thanks! Sure, let me try to reproduce it. It only happens when I use `@gorhom/bottom-sheet` (which internally uses reanimated).

**Comment by jzxchiang1** [comment]
@Kudo I was able to reproduce a crash on Android in a new repo I just created. This time, it crashes with a signal 6 SIGABRT instead of a signal 11 SIGSEGV, but I think they both come from the same root cause...

Please clone this [repo](https://github.com/jzxchiang1/reproduce) locally, run `npm install`, run `npm start`, and then `npm run android`. If you press the button in the App repeatedly, it will eventually cause a crash. It might take up to 10 tries, but it almost always crashes. This issue is not in iOS.

Let me know if you find anything interesting, thanks!

**Comment by jzxchiang1** [comment]
@Kudo Any luck??

**Comment by piaskowyk** [comment]
Because now we maintain two main branches - with Reanimated 3 (building from source) and Reanimated 2 (from binaries)

**Comment by awesome31** [comment]
Hi all! I am getting this error when I try and integrate v8 and reanimated in my project. Let me know what I can do:

`Execution failed for task ':app:mergeBetaReleaseNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'lib/armeabi-v7a/libv8executor.so' from inputs:
      - /builds/anar-app/mobile/node_modules/react-native-v8/android/build/intermediates/library_jni/release/jni
      - /builds/anar-app/mobile/node_modules/react-native-reanimated/android/build/intermediates/library_jni/release/jni
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets`
     
     
     @Kudo @jzxchiang1

**Comment by jzxchiang1** [comment]
@Kudo Thanks for the fix!

Unfortunately, when I install the latest version of react-native-v8 using `npm install "https://github.com/Kudo/react-native-v8#main"` and rerun `npm run android` on my emulator, I encounter this error:

Screen Shot 2022-05-19 at 11 29 36 PM

**Comment by Kudo** [comment]
@jzxchiang1 oh sorry, i still have other fixes to land for reanimated support. would probably be ready next week.

**Comment by Kudo** [comment]
@piaskowyk @jzxchiang1 the pr is updated to reanimated 3 and latest v8 changes from my side. i think the pr is ready to review and test if you would like to.

**Comment by jzxchiang1** [comment]
Awesome, let me give it a try. I'm assuming I must upgrade to reanimated v3 for it to work (so reanimated v2 is not supported for v8). Does that sound accurate?

**Comment by sunnylqm** [comment]
@Kudo 

I got errors like this

```
* What went wrong:
Execution failed for task ':react-native-v8:configureCMakeRelWithDebInfo[arm64-v8a]'.
> [CXX1405] error when building with cmake using /Users/sunny/Documents/app-monorepo/node_modules/react-native-v8/android/CMakeLists.txt: Build command failed.
  Error while executing process /Users/sunny/Library/Android/sdk/cmake/3.18.1/bin/cmake with arguments {-H/Users/sunny/Documents/app-monorepo/node_modules/react-native-v8/android -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=23 -DANDROID_PLATFORM=android-23 -DANDROID_ABI=arm64-v8a -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=/Users/sunny/Library/Android/sdk/ndk/21.4.7075529 -DCMAKE_ANDROID_NDK=/Users/sunny/Library/Android/sdk/ndk/21.4.7075529 -DCMAKE_TOOLCHAIN_FILE=/Users/sunny/Library/Android/sdk/ndk/21.4.7075529/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/Users/sunny/Library/Android/sdk/cmake/3.18.1/bin/ninja -DCMAKE_CXX_FLAGS=-fstack-protector-all -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/sunny/Documents/app-monorepo/node_modules/react-native-v8/android/build/intermediates/cxx/RelWithDebInfo/462m6g4o/obj/arm64-v8a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/sunny/Documents/app-monorepo/node_modules/react-native-v8/android/build/intermediates/cxx/RelWithDebInfo/462m6g4o/obj/arm64-v8a -DCMAKE_BUILD_TYPE=RelWithDebInfo -B/Users/sunny/Documents/app-monorepo/node_modules/react-native-v8/android/.cxx/RelWithDebInfo/462m6g4o/arm64-v8a -GNinja -DANDROID_STL=c++_shared -DBOOST_VERSION=1_63_0 -DBUILD_DIR=/Users/sunny/Documents/app-monorepo/node_modules/react-native-v8/android/build -DRN_DIR=/Users/sunny/Documents/app-monorepo/node_modules/react-native -DV8_ANDROID_DIR=/Users/sunny/Documents/app-monorepo/node_modules/v8-android-jit --clean-first}

  CMake Error: The source directory "/Users/sunny/Documents/app-monorepo/node_modules/react-native-v8/android/--clean-first" does not exist.
  Specify --help for usage, or press the help button on the CMake GUI.
```

**Comment by jzxchiang1** [comment]
@Kudo I think your branch fixes the bug! I tested it with your latest react-native-v8 and latest commit in this PR, and I no longer experience any crashes on Android when opening the bottom sheet. 🎉🎉

However, it was quite painful to get it working with react-native-reanimated v3, which isn't yet stable.

For example, I had to patch react-native-gesture-handler to fix a duplicate class error by returning true [here](https://github.com/software-mansion/react-native-gesture-handler/blob/71c616484ee3b53e0909cd6193dd7cabe8451a1e/android/build.gradle#L56). I also had to patch react-native-bottom-sheet and react-native-redash to not use `Animated.Extrapolate.CLAMP`, which got broken in reanimated v3; the bug is [here](https://github.com/software-mansion/react-native-reanimated/issues/3246).

If I want to use your PR / branch with reanimated v2, would that be easy to do? Do I just rebase your branch onto an older version of reanimated such that it is v2, or does your code actually depend on v3?

**Comment by huduarte** [comment]
> @Kudo I think your branch fixes the bug! I tested it with your latest react-native-v8 and latest commit in this PR, and I no longer experience any crashes on Android when opening the bottom sheet. 🎉🎉
> 
> However, it was quite painful to get it working with react-native-reanimated v3, which isn't yet stable.
> 
> For example, I had to patch react-native-gesture-handler to fix a duplicate class error by returning true [here](https://github.com/software-mansion/react-native-gesture-handler/blob/71c616484ee3b53e0909cd6193dd7cabe8451a1e/android/build.gradle#L56). I also had to patch react-native-bottom-sheet and react-native-redash to not use `Animated.Extrapolate.CLAMP`, which got broken in reanimated v3; the bug is [here](https://github.com/software-mansion/react-native-reanimated/issues/3246).
> 
> If I want to use your PR / branch with reanimated v2, would that be easy to do? Do I just rebase your branch onto an older version of reanimated such that it is v2, or does your code actually depend on v3?

I'm using version 2.8 and this error continues

**Comment by Kudo** [comment]
@sunnylqm looks like a new cmake error. luckily i can repro by using new cmake version. i'll fix it in react-native-v8.

**Comment by Kudo** [comment]
@jzxchiang1 @huduarte for reanimated v2, if reanimated team feels comfortable to backport v8 support in reanimated 2. i can help to create a pr to do that. first of all, i think we should land v8 support to reanimated main branch first (in this case, it's reanimated v3).

**Comment by Kudo** [comment]
> @sunnylqm looks like a new cmake error. luckily i can repro by using new cmake version. i'll fix it in react-native-v8.

@sunnylqm should be fixed in react-native-v8@1.4.1. thanks for reporting this issue to me

**Comment by jzxchiang1** [comment]
So far this is working great for me. Can @piaskowyk or someone else from the reanimated team take a look?

**Comment by jzxchiang1** [comment]
Bump

**Review by graszka22 — COMMENTED** [review]
LGTM, tested with provided testing steps and seems to work ok. The only thing I noticed is that when compiling the app there is a bunch of warnings like this:
```
C/C++: /Users/angelikaserwa/Projects/TestApp/node_modules/react-native-reanimated/android/CMakeLists.txt debug|armeabi-v7a : CMake Warning:
  Manually-specified variables were not used by the project:

    PLAYGROUND_APP_NAME
```

**Review by piaskowyk — APPROVED** [review]
At this moment, It works only with the old architecture, in the future we will work on support for the new architecture.

**Comment by ammarahm-ed** [comment]
@piaskowyk With my PR [here](https://github.com/Kudo/react-native-v8/pull/126) it should work with new architecture too. 

@graszka22 Maybe you can try with my branch of react-native-v8 here which is building correctly on react-native 0.69. 
https://github.com/ammarahm-ed/react-native-v8/tree/fix_rn69

**Comment by piaskowyk** [comment]
@ammarahm-ed Thanks for the info!

**Comment by shamilovtim** [comment]
Hi, what release is this part of? I am trying to get it to work with V2 but it seems that it was only released with one of the v3 release candidates? Confused.

**Comment by Kudo** [comment]
added v8 support for reanimated 2 here: https://github.com/kudo/react-native-reanimated/tree/v8/2.9.1
could install it through `yarn add kudo/react-native-reanimated#v8/2.9.1`

cc @piaskowyk i'm not sure when will you plan to drop reanimated v2 support? if v2 will still be maintained for a while, please also consider backport v8 support to Reanimated2 branch. i can create a pr with [the change](https://github.com/Kudo/react-native-reanimated/commit/2b96fdc9676e83594ab886d02c42a03365fc12f2) for you. the change just adds v8 support and it's building from source, no prebuilt aar.

**Comment by sunnylqm** [comment]
> added v8 support for reanimated 2 here: https://github.com/kudo/react-native-reanimated/tree/v8/2.9.1
> could install it through `yarn add kudo/react-native-reanimated#v8/2.9.1`
> 
> cc @piaskowyk i'm not sure when will you plan to drop reanimated v2 support? if v2 will still be maintained for a while, please also consider backport v8 support to Reanimated2 branch. i can create a pr with [the change](https://github.com/Kudo/react-native-reanimated/commit/2b96fdc9676e83594ab886d02c42a03365fc12f2) for you. the change just adds v8 support and it's building from source, no prebuilt aar.

hi @Kudo thanks for the great work! it works perfectly smooth on android. but your package seems incomplete (missing libs folder which is required by web platform). guess you may forget to run some build process

**Comment by Kudo** [comment]
@sunnylqm please try to use this instead: https://github.com/Kudo/react-native-reanimated/releases/download/v8/2.9.1/react-native-reanimated-2.9.1.tgz
thanks!

**Comment by tomekzaw** [comment]
Hey @Kudo! Are these two lines necessary or can we remove them? 😅 

https://github.com/software-mansion/react-native-reanimated/blob/6497385d4a86c47634f1c22d975a0ce932f45faf/android/CMakeLists.txt#L26

https://github.com/software-mansion/react-native-reanimated/blob/6497385d4a86c47634f1c22d975a0ce932f45faf/android/CMakeLists.txt#L286

Besides, we will backport your PR with V8 support to 2.x branch after we release Reanimated 2.10.

**Comment by Kudo** [comment]
thanks @tomekzaw! that's helpful to have v8 support officially on v2.

these `ignoreMe` are just to reduce the gradle warnings while cmake doesn't use the variables. they are not required but good to have.

**Comment by tomekzaw** [comment]
@Kudo thanks for response, just realised this now but you were 4 minutes faster 😄

I've modified our `CMakeLists.txt` and from now on in some configurations we won't use `${CLIENT_SIDE_BUILD}` either. I'll gather these variables in a single place and add comment `# resolves "Manually-specified variables were not used by the project"` so no one asks in the future, is it okay?

**Comment by Kudo** [comment]
@tomekzaw np! feel free to change the code that makes sense to you.

**Comment by piaskowyk** [comment]
Hey @Kudo! I have already backported support for V8 to the Reanimated2 branch. It will be available in the next release - I hope this week.

**Comment by Kudo** [comment]
excited to know the good news. thanks @piaskowyk!
