### ISSUE TITLE
Exception: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Willham12** [software-mansion/react-native-reanimated#2212]
Fatal Exception: java.lang.NoClassDefFoundError
Failed resolution of: Landroidx/transition/TransitionSet;
com.swmansion.reanimated.transitions.TransitionUtils.inflateGroup (TransitionUtils.java:40)
com.swmansion.reanimated.transitions.TransitionUtils.inflate (TransitionUtils.java:28)
com.swmansion.reanimated.transitions.TransitionModule$1.execute (TransitionModule.java:33)
com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute (UIViewOperationQueue.java:573)
com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:908)
com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:1019)
com.facebook.react.uimanager.UIViewOperationQueue.access$2600 (UIViewOperationQueue.java:47)
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:1079)
com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:29)
com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:175)
com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:85)

**Comment by jmysliv** [comment]
@Willham12 Can you provide some more information that will help us to fix this issue? It will be nice if you provide:
* bug description
* expected and actual behavior
* some code example or steps on how we can reproduce this issue
* your package versions

**Comment by jmysliv** [comment]
@Willham12 I'm closing this issue due to inactivity. If you still encounter this issue feel free to reopen it and please provide the information I described above.

**Comment by Haris-teach** [comment]
@jmysliv I'm facing this issue 
 Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dlopen failed: library "libreanimated.so" not found
 
 and as well this one 
 Error: Exception in HostFunction: java.lang.NoClassDefFoundError: com.swmansion.reanimated.NativeProxy
 
 I just delete my nodemodules and packages.json.lock file 
 
 after reintsalling the packages I'm facing these error's

**Comment by andreasheick-isobar** [comment]
Same issue as @Haris-teach, came after upgrading React Native to 0.70.4 from 0.66.4

**Comment by daba-faith** [comment]
Hello, same issue here

**Comment by chj-damon** [comment]
same issue as @Haris-teach

**Comment by badaz** [comment]
> @jmysliv I'm facing this issue Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dlopen failed: library "libreanimated.so" not found
> 
> and as well this one Error: Exception in HostFunction: java.lang.NoClassDefFoundError: com.swmansion.reanimated.NativeProxy
> 
> I just delete my nodemodules and packages.json.lock file
> 
> after reintsalling the packages I'm facing these error's

Downgrading to 2.14.4 fixed the problem for me

**Comment by marcorios26** [comment]
@badaz what package exactly downgrading do you mean?

**Comment by badaz** [comment]
> @badaz what package exactly downgrading do you mean?

reanimated

**Comment by mianaamirshehzad** [comment]
> > @badaz what package exactly downgrading do you mean?
> 
> react-native-reanimated

This doesn't help at all. Instead, my running app starts misbehaving after installing the above-mentioned version of React Native Reanimated. 
Is there any other way to solve this?

**Comment by badaz** [comment]
> > > @badaz what package exactly downgrading do you mean?
> > 
> > react-native-reanimated
> 
> This doesn't help at all. Instead, my running app starts misbehaving after installing the above-mentioned version of React Native Reanimated. 
> Is there any other way to solve this?

Well it worked for me 3 months ago ;)

**Comment by DaviBFarias** [comment]
> > @jmysliv I'm facing this issue Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dlopen failed: library "libreanimated.so" not found
> > and as well this one Error: Exception in HostFunction: java.lang.NoClassDefFoundError: com.swmansion.reanimated.NativeProxy
> > I just delete my nodemodules and packages.json.lock file
> > after reintsalling the packages I'm facing these error's
> 
> Downgrading to 2.14.4 fixed the problem for me

I was using react-native-reanimated: "^2.13.0" e changing to "^2.14.4" solve to me too. Thanks!

**Comment by rishabsah13** [comment]
@jmysliv iamharisdev same error ..any resolution how to fix this ?
 Error: Exception in HostFunction: java.lang.NoClassDefFoundError: com.swmansion.reanimated.NativeProxy, js engine: hermes

**Comment by rishabsah13** [comment]
@iamharisdev 
same error ..any resolution how to fix this ?
Error: Exception in HostFunction: java.lang.NoClassDefFoundError: com.swmansion.reanimated.NativeProxy, js engine: hermes

**Comment by yshakouri** [comment]
I have the same issue on 2.17.0. I am develope in MAC M1 (aarm64).
Is there any way to solve this?

**Comment by yshakouri** [comment]
[https://github.com/yshakouri/test4](https://github.com/yshakouri/test4)

> I have the same issue on 2.17.0. I am develope in MAC M1 (aarm64). Is there any way to solve this?

**Comment by yshakouri** [comment]
> https://github.com/yshakouri/test4
> 
> > I have the same issue on 2.17.0. I am develope in MAC M1 (aarm64). Is there any way to solve this?

 ERROR  Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.test4-DScGYKrnlKxI6feEiy7bfw==/base.apk"],nativeLibraryDirectories=[/data/app/com.test4-DScGYKrnlKxI6feEiy7bfw==/lib/arm64, /data/app/com.test4-DScGYKrnlKxI6feEiy7bfw==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64]]] couldn't find "libreanimated.so", js engine: hermes
