### ISSUE TITLE
Reanimated 2.7.0 - undefined is not a function via Animated.js

### ISSUE THREAD

**Issue by AlexanderEggers** [software-mansion/react-native-reanimated#3177]
## Description

When updating to the latest version, the following exception is thrown:

> Error: Requiring module "node_modules/react-native-reanimated/src/Animated.js", which threw an exception: TypeError: undefined is not a function, js engine: hermes

### Expected behavior

No error.

### Actual behavior & steps to reproduce

> Error: Requiring module "node_modules/react-native-reanimated/src/Animated.js", which threw an exception: TypeError: undefined is not a function, js engine: hermes

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.68.0     |
| react-native-reanimated              |     2.7.0    |
| NodeJS                               |    16.14.2     |
| Xcode                                |         |
| Java                                 |     11    |
| Gradle                               |         |
| expo                                 |     44    |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by AlexanderEggers** [comment]
It seems like my metro had bad caches and the app is running fine on Android now using 2.7.0.

**Comment by radko93** [comment]
Also had this issue - make sure you run `yarn start --reset-cache` when updating to 2.7.0.
