### ISSUE TITLE
[3.6.0] [Reanimated] [iOS] Build Error - Use of undeclared identifier 'debugger'

### ISSUE THREAD

**Issue by ranaavneet** [software-mansion/react-native-reanimated#5446]
### Description

Hi,

We are getting a build error in xCode 15.0 while building for iOS with reanimated version 3.6.0

Version 3.5.4 works fine.

<img width="832" alt="Screenshot 2023-11-30 at 11 56 09 PM" src="https://github.com/software-mansion/react-native-reanimated/assets/25902558/1134f9c3-867e-4936-b446-648821fe7342">
<img width="848" alt="Screenshot 2023-11-30 at 11 55 54 PM" src="https://github.com/software-mansion/react-native-reanimated/assets/25902558/ce8a3e1a-7216-4126-b14c-6f7236e0dd4a">
<img width="973" alt="Screenshot 2023-11-30 at 11 55 38 PM" src="https://github.com/software-mansion/react-native-reanimated/assets/25902558/f02b1270-dffb-4ec9-9170-c28c92445efe">

### Steps to reproduce

1. React Native 0.70.14
2. Reanimated 3.6.0

### Snack or a link to a repository

-

### Reanimated version

3.6.0

### React Native version

0.70.14

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 15 Pro Max

### Acknowledgements

Yes

**Comment by dprajapati1179** [comment]
Getting same error while using the LTS version.

Showing All Errors Only
/Users/admin/Desktop/dprajapati2311/azure/project_name/node_modules/react-native/ReactCommon/hermes/inspector/RuntimeAdapter.h:76:3: Use of undeclared identifier 'debugger'

**Comment by dprajapati1179** [comment]
@ranaavneet 

The temporary solution I found is to use the lower version without a cap ( ^ ) to get the exact version of reanimated like,

"react-native-reanimated": "3.4.2",

**Comment by adrianha** [comment]
hi @gabrieldonadel @tomekzaw, also found this issue on release build using Xcode 14.2

```
[RNReanimated] Compiling ReanimatedRuntime.cpp
❌ /Users/ssm-user/workspace/Traveloka-B2B-Apps/Tera-Mobile/build-staging-ios/node_modules/react-native/ReactCommon/hermes/inspector/RuntimeAdapter.h:41:11: use of undeclared identifier 'debugger'
  virtual debugger::Debugger &getDebugger() = 0;
          ^
❌ /Users/ssm-user/workspace/Traveloka-B2B-Apps/Tera-Mobile/build-staging-ios/node_modules/react-native/ReactCommon/hermes/inspector/RuntimeAdapter.h:68:7: use of undeclared identifier 'debugger'
      debugger::Debugger &debugger);
      ^
❌ /Users/ssm-user/workspace/Traveloka-B2B-Apps/Tera-Mobile/build-staging-ios/node_modules/react-native/ReactCommon/hermes/inspector/RuntimeAdapter.h:72:3: use of undeclared identifier 'debugger'
  debugger::Debugger &getDebugger() override;
  ^
❌ /Users/ssm-user/workspace/Traveloka-B2B-Apps/Tera-Mobile/build-staging-ios/node_modules/react-native/ReactCommon/hermes/inspector/RuntimeAdapter.h:76:3: use of undeclared identifier 'debugger'
  debugger::Debugger &debugger_;
  ^
  
  The following build commands failed:
	CompileC /Users/ssm-user/Library/Developer/Xcode/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/TeraStaging/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/RNReanimated.build/Objects-normal/arm64/ReanimatedRuntime.o /Users/ssm-user/workspace/Traveloka-B2B-Apps/Tera-Mobile/build-staging-ios/node_modules/react-native-reanimated/Common/cpp/ReanimatedRuntime/ReanimatedRuntime.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNReanimated' from project 'Pods')
(1 failure)
[13:49:07]: Exit status: 65

+------------------------------------------------+
|               Build environment                |
+---------------+--------------------------------+
| xcode_path    | /Applications/Xcode-14.2.0.app |
| gym_version   | 2.216.0                        |
| export_method | ad-hoc                         |
| sdk           | iPhoneOS16.2.sdk               |
+---------------+--------------------------------+
```

is it related with https://github.com/software-mansion/react-native-reanimated/pull/5383?

**Comment by tomekzaw** [comment]
Thanks @ravaavnet for submitting this issue and @adrianha for providing more information!

Could you please check if PR #5450 resolves the error?

**Comment by ranaavneet** [comment]
Hi @tomekzaw! Thanks for looking into it. Yes it does indeed solve this issue. 🙏

**Comment by msageryd** [comment]
Did this fix land in any release yet?
I just upgraded from v2 to 3.6.1 and got this error.
Should I downgrade and wait for 3.6.2?

**Comment by airowe** [comment]
Same question as @msageryd. When is this expected to be released?

**Comment by tomekzaw** [comment]
@msageryd @airowe This is a change in the native code so technically we cannot release a patch with it, we'll need a minor  bump so this will be released in 3.7.0.

However, in the meantime, you can still use a nightly release (`yarn add react-native-reanimated@nightly`) or apply this change on top of 3.6.1 using patch-package.

**Comment by HugoGresse** [comment]
[react-native-reanimated+3.6.1.patch](https://github.com/software-mansion/react-native-reanimated/files/13846259/react-native-reanimated%2B3.6.1.patch)

The patch in question !

**Comment by jamesthesken** [comment]
Thanks @tomekzaw and @HugoGresse ! The patch worked for me: `patch -p1 < react-native-reanimated+3.6.1.patch`

**Comment by aminhdev** [comment]
> [react-native-reanimated+3.6.1.patch](https://github.com/software-mansion/react-native-reanimated/files/13846259/react-native-reanimated%2B3.6.1.patch)
> 
> The patch in question !

Thanks, its working
