### PR TITLE
Cocoapods: Fix deprecated/removed File.exists method

### PR DESCRIPTION
**Pull request by iBotPeaches**
Noticed on accident when I upgraded Ruby on accident to 3 - that my `pod install` failed with:

```
[!] Invalid `Podfile` file: 
[!] Invalid `RNReanimated.podspec` file: undefined method `exists?' for File:Class.

 #  from /Users/xx/iOSProjects/xx-app/node_modules/react-native-reanimated/RNReanimated.podspec:5
 #  -------------------------------------------
 #  reanimated_package_json = JSON.parse(File.read(File.join(__dir__, "package.json")))
 >  config = find_config()
```

Theres a good deal of other errors after I fixed this one on other projects, but this looks like a safe change to get ahead of the future Ruby upgrade. Yeah I did downgrade back to 2.7.5.

## Summary

Resolves the removed method of `File.exists` in Ruby3. The alternative method of `File.exist` is recommended and already exists on 2.5 for no breaking changes.

https://rubyapi.org/2.5/o/file#method-c-exist-3F

## Test plan

A local working `pod install`

### CODE REVIEW

**Review by piaskowyk — APPROVED** [review]
Thanks for your PR! 🚀

**Comment by MarcosB7** [comment]
I'm getting this error too. But I don't understand how I can fix it with this, can you explain?

**Comment by iBotPeaches** [comment]
> I'm getting this error too. But I don't understand how I can fix it with this, can you explain?

I thought my explanation was pretty detailed - what part are you lost on?

**Comment by MarcosB7** [comment]
Sorry, I'm a little bit new. If I update cocoapods would the problem be solved?

**Comment by raulglezrdguez** [comment]
go to:
Project/node_modules/react-native-reanimated/scripts/reanimated_utils.rb
and change File.exists for File.exist

**Comment by LukasMod** [comment]
If you use patch package here is a file working with 2.12:

**react-native-reanimated+2.12.0.patch**

```
diff --git a/node_modules/react-native-reanimated/scripts/reanimated_utils.rb b/node_modules/react-native-reanimated/scripts/reanimated_utils.rb
index 481cb3a..b613361 100644
--- a/node_modules/react-native-reanimated/scripts/reanimated_utils.rb
+++ b/node_modules/react-native-reanimated/scripts/reanimated_utils.rb
@@ -1,6 +1,6 @@
 def try_to_parse_react_native_package_json(node_modules_dir)
   react_native_package_json_path = File.join(node_modules_dir, 'react-native/package.json')
-  if !File.exists?(react_native_package_json_path)
+  if !File.exist?(react_native_package_json_path)
     return nil
   end
   return JSON.parse(File.read(react_native_package_json_path))
```
