### PR TITLE
Old implementation of bezier function

### LINKED ISSUE #2766: _reactNativeReanimated.Easing.bezier is not a function _reactNativeReanimated.Easing.bezier is an instance of Object after upgrading to 2.3.1
## Description

After upgrading my expo project from sdk43 to 44. 
This error came up.

_reactNativeReanimated.Easing.bezier(0.16, 1, 0.3, 1) is not a function _reactNativeReanimated.Easing.bezier(0.16, 1, 0.3, 1) is an instance of Object  

### Expected behavior
should be running just like before
### Actual behavior & steps to reproduce
breaking

## Steps to reproduce
...

    const animatedBoxProps = useAnimatedProps(
    () => ({
      stroke: interpolateColor(
        Easing.bezier(0.16, 1, 0.3, 1)(progress.value),
        [0, 1],
        [boxOutlineColor, highlightColor],
        'RGB'
      ),
      fill: interpolateColor(
        Easing.bezier(0.16, 1, 0.3, 1)(progress.value),
        [0, 1],
        ['#00000000', highlightColor],
        'RGB'
      )
    }),
    [highlightColor, boxOutlineColor]
  );        

## Package versions
-reanimated: 2.3.1

- React Native Reanimated: 2.3.1

### PR DESCRIPTION
**Pull request by piaskowyk**
## Description

During the performance optimization, I changed the implementation of `Easing.bezier` function, now return an object instead of a plain function, so I added the old implementation in `Easing.bezierFn`

Fixes #2766

### CODE REVIEW

**Review by tomekzaw — APPROVED** [review]
👍
