### ISSUE TITLE
[RN 0.66] 'boost/preprocessor/control/expr_iif.hpp' file not found

### ISSUE THREAD

**Issue by KingAmo** [software-mansion/react-native-reanimated#2434]
## Description
brand new RN `0.66.rc.3` project, build failed on iOS

### Expected behavior

RN `0.66.rc.3` build success on iOS 

## Package versions
```
System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 32.48 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.22.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 21, 23, 25, 26, 27, 28, 29, 30
      Build Tools: 23.0.1, 26.0.1, 26.0.2, 27.0.3, 28.0.3, 29.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.0-rc.3 => 0.66.0-rc.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- React Native: `0.66.0-rc.3`
- React Native Reanimated: `2.2.2`

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by hsavit1** [comment]
confirmed still a problem with 0.66-rc4

tested with RN v2.2.2 and 2.3.0-alpha3

**Comment by MonsterAnan** [comment]
+1

**Comment by bneigher** [comment]
+1

**Comment by nomi9995** [comment]
I tested master it is working with  React Native 0.66

Attaching it below in case it helps someone.

[react-native-reanimated-2.3.0-beta.2.tgz](https://www.dropbox.com/s/jo3hr9zcqd46nvu/react-native-reanimated-2.3.0-beta.2.tgz?dl=0)

down above pack and pasted on your project root. It can be used by changing the entry in `package.json` to:
```json
"react-native-reanimated": "file:./react-native-reanimated-2.3.0-beta.2.tgz",
```

**Comment by nomi9995** [comment]
@KingAmo now you can install  `2.3.0-beta.2` version which have support for  react native 0.66
 https://github.com/software-mansion/react-native-reanimated/releases/tag/2.3.0-beta.2

**Comment by tapz** [comment]
I tried to build with the RN 0.66.0 release version.

With reanimated 2.2.2 I get this error:

`'boost/operators.hpp' file not found`

and with 2.3.0-beta.2 this:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RNSScreenView", referenced from:
      objc-class-ref in REAUIManager.o
ld: symbol(s) not found for architecture arm64
```

**Comment by piaskowyk** [comment]
Does it problem still occur on Reanimated 2.3.1?

**Comment by tapz** [comment]
@piaskowyk I haven't seen this error with 2.3.1.

**Comment by jakub-gonet** [comment]
I assume this issue was fixed in 2.3.1. Please reply if you experience this problem on the latest version.
