### ISSUE TITLE
[3.4.0 nightly] isWeb is not a function on decay.ts

### ISSUE THREAD

**Issue by efstathiosntonas** [software-mansion/react-native-reanimated#4656]
### Description

On yesterday’s nightly `3.4.0-nightly-20230629-1fa467e6a`  it throwed this error:

`facebook::jsi::JSError: isWeb is not a function (it is Object)

TypeError: isWeb is not a function (it is Object)
    at anonymous (JavaScript:1:103)
    at anonymous (JavaScript:1:1813)
    at apply (native)
    at runWorklet (JavaScript:1:207)
    at anonymous (JavaScript:1:886)
    at handleAndFlushAnimationFrame (JavaScript:1:147)

0 unknown file -0x4 unknown method`

I use this library to display full screen gallery: https://github.com/Flair-Dev/react-native-awesome-gallery

### Steps to reproduce

1. Install yesterday’s nightly `3.4.0-nightly-20230629-1fa467e6a`

### Snack or a link to a repository

*

### Reanimated version

3.4.0 nighlty 

### React Native version

0.72.1

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

iPhone 13

### Acknowledgements

Yes

**Comment by efstathiosntonas** [comment]
some more context, while swiping down the image I get this error:  

![Simulator Screenshot - iPhone 14 Pro Max - 2023-07-01 at 19 32 53](https://github.com/software-mansion/react-native-reanimated/assets/717975/f1e79bbd-835f-427d-b53f-cf2dfad7fc2c)

https://github.com/software-mansion/react-native-reanimated/blob/7143b1e049ba721b51ba570e2e22eb7f00672196/src/reanimated2/animation/decay.ts#L52

the error on first comment is from Bugsnag and it's misleading :(

**Comment by efstathiosntonas** [comment]
after reverting this commit https://github.com/software-mansion/react-native-reanimated/commit/bbc755bd685435392cf37e4e69f0deb27d18aa37 everything is back to normal.

**Comment by tomekzaw** [comment]
@efstathiosntonas Thanks a lot for the investigation! This is the change that I've introduced in #4594:

<img width="675" alt="Zrzut ekranu 2023-07-2 o 10 28 34" src="https://github.com/software-mansion/react-native-reanimated/assets/20516055/d3b8b9d5-5f27-48fd-adb8-72f21c6b6088">

For some reason, this assignment was moved to inside a worklet in #4519, probably while resolving Git conflicts:

<img width="717" alt="Zrzut ekranu 2023-07-2 o 10 29 14" src="https://github.com/software-mansion/react-native-reanimated/assets/20516055/cde1b664-8da2-4555-85e6-c5eb6699e4f6">

We will submit a fix soon, thanks again!

**Comment by efstathiosntonas** [comment]
great, thanks @tomekzaw, keep it up!

**Comment by tomekzaw** [comment]
@efstathiosntonas Obviously, if you would like to submit a PR, feel free to do so (since you're the one who found the root cause of the issue and we appreciate it!)

**Comment by angelica-snowit** [comment]
I got this error in production, tracked by crashlitycs, on v3.4.0

**Comment by angelica-snowit** [comment]
I confirm the error in production (a lot of logs) also on v3.5.4

**Comment by tomekzaw** [comment]
@angelica-snowit how about 3.6.1?

**Comment by m-bert** [comment]
I looked into this stack trace and unfortunately it doesn't help much. The error `Object is not a function` is too general to tell what actually fails. Would you be able to give as any additional information? Like a part of source code which fails? I know you said that you only have logs from crashlitycs, but without further information it will be difficult to figure out why your app crashes.

**Comment by angelica-snowit** [comment]
> I looked into this stack trace and unfortunately it doesn't help much. The error `Object is not a function` is too general to tell what actually fails. Would you be able to give as any additional information? Like a part of source code which fails? I know you said that you only have logs from crashlitycs, but without further information it will be difficult to figure out why your app crashes.

Sadly, this are the only info I have, the log is the full Crashlytics log.
I just can tell the error is inside the `handleAndFlushAnimationFrame` function.

**Comment by Latropos** [comment]
Closing, since the bug in issue description "isWeb is not a function on decay.ts" is already solved
