### ISSUE TITLE
[3.7.0] Data type not recognized by value unpacker. at valueUnpacker (WorkletRuntime::WorkletRuntime:1:1477)

### ISSUE THREAD

**Issue by efstathiosntonas** [software-mansion/react-native-reanimated#5660]
### Description

Cannot reproduce it locally, for now I've encountered in production builds on Androids 11,12,13,14. 

Error: 
`Data type not recognized by value unpacker. at valueUnpacker (WorkletRuntime::WorkletRuntime:1:1477)`

Full stacktrace: 

```
﻿﻿com.facebook.jni.CppException: [Reanimated] Data type not recognized by value unpacker.

Error: [Reanimated] Data type not recognized by value unpacker.
    at valueUnpacker (WorkletRuntime::WorkletRuntime:1:1477)
        at com.swmansion.reanimated.AndroidUIScheduler.triggerUI(AndroidUIScheduler.java:-2)
        at com.swmansion.reanimated.AndroidUIScheduler$1.run(AndroidUIScheduler.java:24)
        at com.swmansion.reanimated.AndroidUIScheduler$2.runGuarded(AndroidUIScheduler.java:43)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:29)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:250)
        at android.app.ActivityThread.main(ActivityThread.java:7755)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

### Steps to reproduce

1. Updated to 3.7.0
2. crashes

### Snack or a link to a repository

no-repo-cannot-reproduce

### Reanimated version

3.7.0

### React Native version

0.73.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Release app & production bundle

### Device

Real device

### Device model

LG G8 ThinQ™ (LM-G820), Mi Note 10, Galaxy S22 Ultra (SM-S908U), moto g(8) power

### Acknowledgements

Yes

**Comment by joe-sam** [comment]
I don't know if this is related but while testing a PR #5216 I found that some AP initWithContext/NativeProxy I had to add a non optional parameter which is a **valueUnpackerCode** of type _String_.  You may have to include this missing argument/type in some function call or provide its default value.

**Comment by efstathiosntonas** [comment]
@joe-sam thanks for the heads up, can you please be more specific? What is AP? 

where this code should be placed? 

```java
public void initWithContext(ReactApplicationContext reactApplicationContext, String valueUnpackerCode) {
   mReactApplicationContext = reactApplicationContext;
   mNativeProxy = new NativeProxy(reactApplicationContext, valueUnpackerCode);
   mAnimationManager.setAndroidUIScheduler(getNativeProxy().getAndroidUIScheduler());
   compatibility = new ReaCompatibility(reactApplicationContext);
   compatibility.registerFabricEventListener(this);
 }
```

**Comment by joe-sam** [comment]
@efstathiosntonas

AP was a  typo I meant API interface. valueUnpackerCode is a new argument to initContext/nativeProxy. You possibly may have multiple mismatched library versions that might be trying to invoke the reanimated API from the earlier/later library interface. 
I had to pin the resolutions for the peer dependency in my _package.json_ before my incompatibility issues went away.

This code snippet comes from [here](https://github.com/software-mansion/react-native-reanimated/blob/main/android/src/main/java/com/swmansion/reanimated/NodesManager.java) .

**Comment by anders-friis-topdk** [comment]
This issue is causing many crashes in my project after updating to React Native 0.73.4, Reanimated 3.7.0 and old architecture. It crashes often but not consistently so it's hard to come up with a repro but I am looking into it. 
I also tried downgrading to previous Reanimated version, but it doesn't seem to be compatible with RN 0.73.4 so we are stuck with these crashes at the moment. 
I checked our yarn.lock file and it doesn't seem there are multiple reanimated versions in play.  

Can you elaborate on the potential fix your mention with `initWithContext`, @efstathiosntonas or @joe-sam ?

**Comment by efstathiosntonas** [comment]
@anders-friis-topdk use version `3.6.2`, it works with rn 0.73.

unfortunately I do not have the time to look into this at this moment, I've downgraded to 3.6.2 for the time being.

**Comment by anders-friis-topdk** [comment]
@efstathiosntonas 
I just tried downgrading to 3.6.2 and this time I succeeded. Must have been some cache problem last time I tried. 
I cannot get the app to crash now so that seems to solve it for now :) Thanks!

**Comment by joe-sam** [comment]
I am on RN 0.72.10. 
I found that multiple package.json peer libraries use different peer dependencies of _react-native-reanimated_ which were completely version confused although this did not show up in _yarn.lock_ 
So when resolving  I did the following standard methods to try to flush the cache(s?) and  pin the version. This worked locally in \_\_DEV\_\_ but don't know whether this works with PROD.
I also pinned the peer dependency resolution of reanimated library by injecting this into _package.json_
```

   "resolutions": {
    "react-native-reanimated": "3.7.0"
   }
```

**Comment by efstathiosntonas** [comment]
@tjzel @tomekzaw hey guys, care to explain why this might be throwing and if there's a way to track it down on our animated hooks? Thanks!

**Comment by talaikis** [comment]
Same with RN 0.73.4. Had no such problem with RN 0.72 and 3.3.0. Resolution does nothing in prod.

**Comment by tomekzaw** [comment]
Hey @efstathiosntonas, thanks for reporting this issue.

> I don't know if this is related but while testing a PR https://github.com/software-mansion/react-native-reanimated/pull/5216 I found that some AP initWithContext/NativeProxy I had to add a non optional parameter which is a valueUnpackerCode of type String. You may have to include this missing argument/type in some function call or provide its default value.

@joe-sam This API is private and used only internally, you should never need to make any changes to it.

> You possibly may have multiple mismatched library versions that might be trying to invoke the reanimated API from the earlier/later library interface. I had to pin the resolutions for the peer dependency in my package.json before my incompatibility issues went away.

@joe-sam Having multiple versions of Reanimated installed at once usually breaks things. That's why in #4914 (released in 3.6.0) we added a runtime check that asserts that only one instance of Reanimated is present:

https://github.com/software-mansion/react-native-reanimated/blob/b9caec4948f2c8b288a2f748a4741c86d2d1e5ea/src/reanimated2/NativeReanimated/NativeReanimated.ts#L71-L81

For more details, see https://docs.swmansion.com/react-native-reanimated/docs/guides/troubleshooting/#multiple-versions-of-reanimated-were-detected.

We recommend the solution from https://github.com/software-mansion/react-native-reanimated/issues/5660#issuecomment-1944337413.

> hey guys, care to explain why this might be throwing and if there's a way to track it down on our reanimated hooks?

Sure, the error comes from this `else` statement:

https://github.com/software-mansion/react-native-reanimated/blob/b9caec4948f2c8b288a2f748a4741c86d2d1e5ea/src/reanimated2/valueUnpacker.ts#L65-L67

When copying JS values from RN runtime to UI runtime (e.g. worklet closure), they are first serialized from JS values to C++ shareables (intermediate format, runtime-agnostic data structures) and then parsed from C++ shareables to JS values. 

`valueUnpacker` is a function used to parse more complex objects like worklets or remote functions.

The error in the issue description states that `valueUnpacker` cannot re-create passed object.

**Comment by efstathiosntonas** [comment]
thanks @tomekzaw for the detailed explanation. 

It seems that we need to revisit our animated hooks and methods and change things around. This is not an issue with 3.6.2 so recent changes have caused this. 

Question is, are you going to revisit this else/if function and improve it/fix it? If not, this is breaking the API on several npm modules with reanimated as a dep since according to my bugsnag reports there are 2 npm modules that causing this. It's really hard to reproduce though 🤷‍♂️

**Comment by tomekzaw** [comment]
Honestly, I'd like to eliminate `valueUnpacker` as soon as possible. This function is implemented in JS and we need to pass its source code from JS to native side in `installTurboModule` which makes things overly complicated. Currently, it's used in three different places and we can decouple them:
* `ShareableWorklet::toJSValue` &ndash; `valueUnpacker` creates and memoizes worklets
* `ShareableHandle::toJSValue` &ndash; `valueUnpacker` memoizes handles
* `ShareableRemoteFunction::toJSValue` &ndash; `valueUnpacker` adds logic for "Tried to synchronously call" error

I think I will submit a PR with a small refactor.

**Comment by tomekzaw** [comment]
@efstathiosntonas As described above, `valueUnpacker` is responsible for converting worklets, remote functions and values with initializers. However, the provided error clearly states that it has been called for something else that does not fall into any of these categories. This means that even if we refactor each individual branch, the error is still likely to persist.

At this point, we need to know what object caused `valueUnpacker` to fail. However, you have mentioned that you cannot reproduce the issue locally. Is there any way we could at least see what object causes the error? This could be easily done by appending the error message with the string representation of the object to unpack:

```diff
  } else { 
-   throw new Error('[Reanimated] Data type not recognized by value unpacker.'); 
+   throw new Error('[Reanimated] Data type not recognized by value unpacker.' + ' String(objectToUnpack)); 
  } 
```

**Comment by alexstanbury** [comment]
I'm having the same issue and can recreate it in my app by following a certain sequence. With your code amendment `String(objectToUnpack)` I get `[Object object]` appended to the end, and with ` JSON.stringify(objectToUnpack, null, 2)` I get `{}`, an empty object.

**Comment by efstathiosntonas** [comment]
thanks @alexstanbury, @tomekzaw no matter how many times I try I cannot get it to crash in my environment, sorry 🫤 

The part of the code where this crashes was working perfectly fine on < 3.7.0, it srarted showing up after the upgrade on my bugsnag logs.

**Comment by tomekzaw** [comment]
@alexstanbury Can you try `_toString(objectToUnpack)` instead?

**Comment by joe-sam** [comment]
The current stack trace is useless as when this error/exception occurs a redundant stack trace is printed. 
My suggestion is since all supported versions of react-native can finally handle non-standard error objects (https://github.com/facebook/react-native/pull/42079) perhaps a stack trace of the other thread could be injected into the wrapper object (_objectToPack_) before it is initially marshalled/serialized by the _valuePacker_. This can be useful device for debugging and it would at the very minimum  show the file where the exception was actually thrown. You can delete this stacktrace(or remove the wrapper) if un-marshalled/deserialized successfully or enable this only during development.

**Comment by tomekzaw** [comment]
@joe-sam Just to confirm that I understand your proposal correctly &ndash; your idea is to get the stack trace from the RN runtime when the value is serialized from JS value into a C++ intermediate form (technically, this is called `makeShareableClone`) and then include that string in the C++ serializable form, so that we can access it when parsing back from C++ to JS value in `valueUnpacker`?

This way we would at least know the origin of the values copied into the UI runtime, in terms of what functions passed them to `makeShareableClone`.

**Comment by alexstanbury** [comment]
I'll be testing & recreating this morning so if you can provide instructions on how to make the above changes, I'll give it a go.

**Comment by dpyeates** [comment]
I am seeing this in production as well. RN0.73.4, Reanimated 3.7.0.

![Screenshot 2024-02-22 at 08 03 37](https://github.com/software-mansion/react-native-reanimated/assets/944670/66605826-f735-4a89-88e1-50e59179d738)

**Comment by tomekzaw** [comment]
@dpyeates Thanks for letting us know!

@alexstanbury Great to hear, thanks in advance! Let's start with the following change that should print more information about the failing value:

```diff
  } else { 
-   throw new Error('[Reanimated] Data type not recognized by value unpacker.'); 
+   throw new Error('[Reanimated] Data type not recognized by value unpacker.' + ' _toString(objectToUnpack)); 
  } 
```

**Comment by SukumarRN7** [comment]
<img width="1152" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/115766773/1cd90fa6-66f1-4f77-814f-90a1323923a1">

Happening on  
 -  "react-native": "^0.72.0",
 -  "react-native-reanimated": "^3.6.1",
 
 This was working fine with the same above versions since 2 months i guess, 
 and suddenly it started coming up since yesterday and frequency is quiet high as well.

**Comment by joe-sam** [comment]
@tomekzaw Yes, essentially correct (and could be hidden behind a feature flag), so as to easily create a reproducer which is only possible if we know the context of the exception.

**Comment by sagar-tomar-groww** [comment]
@tomekzaw I was able to produce the crash once in an hour almost after multiple hit and trials. 
Not able to consistently repro it but it's definitely a crash. It got reported on Bugsnag with similar messaging. 
Can you help me could it be due to usage of deprecated ` Extrapolate.CLAMP` instead of `Extrapolation.CLAMP` in  `interpolate(scrollY.value, [-ANIMATION_HEIGHT, 0], [-ANIMATION_HEIGHT, 0], Extrapolate.CLAMP);` ? 
Can you help us identify which all API and how `valueUnpacker` gets used so that we can debug further ?

**Comment by tjzel** [comment]
@sagar-tomar-groww Using the deprecated `Extrapolate` has no connection to that. Deprecation token is only present in the ambient type context of TypeScript and has no effect on runtime. I will provide you with `patch-package` file soon so we could extract more information about the crash.

**Comment by tjzel** [comment]
[react-native-reanimated+3.7.0.patch](https://github.com/software-mansion/react-native-reanimated/files/14384493/react-native-reanimated%2B3.7.0.patch)

[react-native-reanimated+3.7.1.patch](https://github.com/software-mansion/react-native-reanimated/files/14384494/react-native-reanimated%2B3.7.1.patch)

@sagar-tomar-groww @dpyeates @efstathiosntonas @joe-sam 

Here, please use patch-package according to your installed version, rebuild the app and paste the error you get with it applied.

**Comment by tomekzaw** [comment]
By any chance, do you have access to C++ stack trace? This would help us a lot (we only have Java stack trace which isn't very helpful).

**Comment by sagar-tomar-groww** [comment]
Missing stacktrace
<img width="1405" alt="Screenshot 2024-02-23 at 6 02 45 PM" src="https://github.com/software-mansion/react-native-reanimated/assets/113590267/fd67ec92-cfde-4029-a218-6593b628b928">

Just to update: While using build with v3.7.0, I experienced 3-4 crash in a span of ~5 hours. Unfortunately there is no pattern to it, on the very next launch, things works fine. 
I'll use the shared patch package to see if we get some more details in the crash report

**Comment by efstathiosntonas** [comment]
@tomekzaw managed to replicated it.

```
libc++abi: terminating due to uncaught exception of type facebook::jsi::JSError: [Reanimated] Data type not recognized by value unpacker.{"`

Error: [Reanimated] Data type not recognized by value unpacker.{"`
    at valueUnpacker (WorkletRuntime::WorkletRuntime:1:1477)
```

**Comment by efstathiosntonas** [comment]
Yes, patch is applied

**Comment by tjzel** [comment]
🤯

**Comment by efstathiosntonas** [comment]
i got xcode trace but can't copy all the lines. 
![Screenshot 2024-02-23 at 15 46 21](https://github.com/software-mansion/react-native-reanimated/assets/717975/36963c16-703f-4d9e-b2ce-7ba3ac6a5fe1)

**Comment by tjzel** [comment]
Can you post the screen of the exception itself? Also, do you have a reproduction?

**Comment by efstathiosntonas** [comment]
@tomekzaw no reproduction, sorry. 

let me know if you want to zoom and share screen to check the xcode stacktrace

**Comment by tjzel** [comment]
The stacktrace is not very useful unfortunately, but maybe (hopefully) you haven't copied the whole error? This is bizzare 🤯

**Comment by tjzel** [comment]
Ah so actually the backtick is a part of the thing... 🤔

**Comment by efstathiosntonas** [comment]
seems like an object with a string that contains template literals, makes no sense

**Comment by efstathiosntonas** [comment]
@tjzel spotted the correct trace, stupid Xcode was showing me the wrong one. I expanded all threads and found it. Looking it now

**Comment by efstathiosntonas** [comment]
@tjzel I think this is the last thing called before the crash:

![Screenshot 2024-02-23 at 16 45 02](https://github.com/software-mansion/react-native-reanimated/assets/717975/60a26359-736b-427e-8f89-0708f2b44aa1)

**Comment by tjzel** [comment]
Unfortunately this isn't very informative as well. Did you get it from the same stack trace you posted or from different one?

**Comment by idlework** [comment]
Same issue occurs on a Samsung S21 device in our app with react native v72.10 and Reanimated v3.7.1.

I dont have a reproduction at this moment.

Sentry Error:
```[Reanimated] Data type not recognized by value unpacker.

Error: [Reanimated] Data type not recognized by value unpacker.
    at valueUnpacker (WorkletRuntime::WorkletRuntime:1:1477)```

Stack trace:
```
com.swmansion.reanimated.AndroidUIScheduler in triggerUI
com.swmansion.reanimated.AndroidUIScheduler$1 in run at line 24
com.swmansion.reanimated.AndroidUIScheduler$2 in runGuarded at line 43
com.facebook.react.bridge.GuardedRunnable in run at line 30 
android.os.Handler in handleCallback at line 958
android.os.Handler in dispatchMessage at line 99
android.os.Looper in loopOnce at line 205
android.os.Looper in loop at line 294
android.app.ActivityThread in main at line 8248
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 552
com.android.internal.os.ZygoteInit in main at line 971com.swmansion.reanimated.AndroidUIScheduler in triggerUI
com.swmansion.reanimated.AndroidUIScheduler$1 in run at line 24
com.swmansion.reanimated.AndroidUIScheduler$2 in runGuarded at line 43
com.facebook.react.bridge.GuardedRunnable in run at line 30
android.os.Handler in handleCallback at line 958
android.os.Handler in dispatchMessage at line 99
android.os.Looper in loopOnce at line 205
android.os.Looper in loop at line 294
android.app.ActivityThread in main at line 8248
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 552
com.android.internal.os.ZygoteInit in main at line 971
```

**Comment by tjzel** [comment]
Since the stack traces aren't any useful, logging the troublesome value didn't give any hints either, and we cannot reproduce it, we have to somehow debug this incrementally.

Please try using the following patch on 3.7.1 instead, rebuild your apps and see if you get errors then and what do they say.
[react-native-reanimated+3.7.1.patch](https://github.com/software-mansion/react-native-reanimated/files/14406248/react-native-reanimated%2B3.7.1.patch)

**Comment by RRaideRR** [comment]
Applied the patch:

```
[Reanimated] Data type in category "Handle" not recognized by value unpacker: "{"`Gq": [Function bound anonymous]}".

Error: [Reanimated] Data type in category "Handle" not recognized by value unpacker: "{"`Gq": [Function bound anonymous]}".
    at valueUnpacker (WorkletRuntime::WorkletRuntime:1:1489)
```

**Comment by tjzel** [comment]
Thanks @RRaideRR. This gives us some more information but it's still hard to tell exactly what's causing trouble.

This patch has some more assertions and some changes that were added in this pipeline. Please try it and report the error/lack of it afterwards. 
[react-native-reanimated+3.7.1.patch](https://github.com/software-mansion/react-native-reanimated/files/14434674/react-native-reanimated%2B3.7.1.patch)

**Comment by RRaideRR** [comment]
hey @tjzel,

thanks for your effort looking into this. The error still exists. Hopefully it helps you debugging it further :). 
<img width="667" alt="Bildschirmfoto 2024-02-29 um 10 37 43" src="https://github.com/software-mansion/react-native-reanimated/assets/3411292/13b1c694-ca01-4802-971c-7da384063b1e">

**Comment by efstathiosntonas** [comment]
@RRaideRR I don’t think this stacktrace is the same issue like this one, please correct me if I’m wrong.

**Comment by RRaideRR** [comment]
@efstathiosntonas 

Hey initially I had the same stack trace / error message as you. In my understanding, the patches that @tjzel provided added different error message to help them track down the issue. 

So the error is still the same, but the error messages are now different because I applied the patches.

What happens in your code when you are applying the patches? I would say that you probably also gonna get different error messages then.

**Comment by RRaideRR** [comment]
Hey @tjzel ,

I thought about giving you some additional information for my use case before but decided against it because the whole thing doesn't make any sense to me.


- The thing only occurs on one of my testing devices: Google Pixel 2.
- I render a deck of cards. Each card has a PanGesture handler from rngh wrapping it. I'm doing a lot of reanimated stuff inside the components. Everything works.
- When the user logs out, [the navigation stack is exchanged ](https://reactnavigation.org/docs/auth-flow)
- When the user logs in again, and the deck of cards is about to be rendered, the whole app crashes with the above error.
- When I comment out the PanGesture handler everything works. 

... doesn't make any sense to me at all :-D

**Comment by tjzel** [comment]
@Elrohil44 does it happen only in production?

**Comment by efstathiosntonas** [comment]
@Elrohil44 thanks for the reproducer. Managed to reproduce it and I get the same stack trace like @RRaideRR right [above](https://github.com/software-mansion/react-native-reanimated/issues/5660#issuecomment-1970755397).

@tjzel tested it in debug mode.

**Comment by Elrohil44** [comment]
@tjzel it is happening for me in debug mode in emulator

**Comment by Elrohil44** [comment]
Well, for me it also happens randomly. Sometimes it happens every 5 minutes and sometimes it is running for several minutes without error. In my case, I am testing it on Android, so maybe indeed Android has a higher chance to trigger error

**Comment by SukumarRN7** [comment]
@tjzel this is also happening on IOS.

in production, although it didnot  print any stack trace.

<img width="1388" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/115766773/74350c68-836e-4dd0-ae04-0a72950ef209">

**Comment by tsogzark** [comment]
I have encountered the same stack trace. This issue manifests on my Android and iPad devices with an approximate probability of 1 in 50.Thanks to guys who are working on the issue.

version: 3.7.2

**Comment by aspidvip** [comment]
me to

**Comment by tjzel** [comment]
Thanks everyone for your effort here. Thanks to reproduction postem by @Elrohil44 we managed to find the underlying problem and it's a race condition. We will soon patch this up and try to release Reanimated 3.8.0 shortly afterwards.

**Comment by tjzel** [comment]
![image](https://github.com/software-mansion/react-native-reanimated/assets/40713406/dcdd6bcd-c799-48c6-a6fe-5cacfa27ed13)

**Comment by tjzel** [comment]
It's an absolute priority for us to ship production crash fixes asap 🚤

**Comment by angelica-snowit** [comment]
still waiting a patch for this :'(

**Comment by tmitchel2** [comment]
I downgraded to 3.6.3 but im still getting this issue.  Is that expected and is it known which version is the last known good version?

**Comment by efstathiosntonas** [comment]
@tmitchel2 this started after upgrading to 3.7.0, never encountered it on 3.6.2, it shouldn't happen in 3.6.3 since it only included some web fixes in comparison with 3.6.2 according to the release notes. 

Did you cleaned your project and metro cache after downgrading?

**Comment by SukumarRN7** [comment]
@tmitchel2 Can you give a look on ur npm/yarn lock file
 - check for if reanimated is pointing to 3.6.2 but is still referring to use 3.7.0 because of "^" sign. 
 You might need to change that explicitly to use 3.6.2 .

**Comment by tmitchel2** [comment]
I had the exact same thought and when I downgraded again I locked it down to 3.6.1, but actually looking back in git I can see it was indeed still using 3.7.1 in the lockfile

(facepalm)

:)

**Comment by efstathiosntonas** [comment]
3.8.0 is out, thanks @tjzel ❤️

**Comment by tomgreco** [comment]
I'm getting this error on 3.8.1 with jest.

`    node_modules/react-native-reanimated/src/reanimated2/valueUnpacker.ts:67:94 - error TS2552: Cannot find name '_toString'. Did you mean 'toString'?

    67       `[Reanimated] Data type in category "${category}" not recognized by value unpacker: "${_toString(
                                                                                                    ~~~~~~~~~

      node_modules/typescript/lib/lib.dom.d.ts:18181:18
        18181 declare function toString(): string;`

**Comment by andrecrimb** [comment]
I'm still getting this in 3.8.1.

**Comment by quantumperception** [comment]
Getting this in jest, Reanimated 3.11.0, RN 0.74.1

**Comment by quantumperception** [comment]
I was getting this in Jest tests. I was mocking using `react-native-reanimated/mock`, solved it by using just `jest.mock('react-native-reanimated')` instead.

RN 0.74.1, Expo SDK 51, Reanimated 3.10.1
