### ISSUE TITLE
[iOS] Chrome debugger stop working on 2.3.0, but woks with 2.2.4

### ISSUE THREAD

**Issue by Romick2005** [software-mansion/react-native-reanimated#2728]
After updating to the latest version of react-native-reanimated 2.3.0 from 2.2.4 Chrome debugger app freezes on initial loading phase showing spinner without any errors.

**Comment by tomgreco** [comment]
global.performance.now() is not a function is the error. 
Very valid issue.

**Comment by piaskowyk** [comment]
Hey, I have already checked Chrome Debugger on iOS, and everything works. Could you provide me a repo to reproduce your problem?

**Comment by piaskowyk** [comment]
We have same thread here - https://github.com/software-mansion/react-native-reanimated/issues/2671 I welcome to discussion there.
