### ISSUE TITLE
No AAR for react-native-reanimated found. Attempting to build from source.

### ISSUE THREAD

**Issue by salman-naheed** [software-mansion/react-native-reanimated#4742]
### Description

> Configure project :react-native-reanimated
No AAR for react-native-reanimated found. Attempting to build from source.
Android gradle plugin: 7.3.1
Gradle: 7.5.1

react-native-reanimated version: 3.3.0,
react: 18.2.0,
react-native: 0.71.8,

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> java.lang.NullPointerException
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

What causes this issue on my KDE linux system?
My team mate runs the same project and it works fine on his system. But we are unable to investigate what is missing.
Please let me know if any further details are required.

### Steps to reproduce

1. Using both NPM and YARN but same results
2. removed .lock.json files
3. also used ./gradlew clean but same results

### Snack or a link to a repository

project repo is private

### Reanimated version

3.3.0

### React Native version

0.71.8

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

Android emulator

### Device model

Android emulator

### Acknowledgements

Yes

**Comment by Ahmed-Imam** [comment]
any updates on this ?

**Comment by pniby** [comment]
Got the same issue after upgrading RN from 0.68.2 to 0.72.3. Any solutions?

**Comment by xerdnew** [comment]
Same problem here on 0.72.3.

`> Configure project :react-native-reanimated
No AAR for react-native-reanimated found. Attempting to build from source.
Android gradle plugin: 7.4.2
Gradle: 8.0.1
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Task :app:compileDebugJavaWithJavac FAILED
C:\LOCATION\MainActivity.java:11: error: cannot find symbol
  protected void onCreate(Bundle savedInstanceState) {
                          ^
  symbol:   class Bundle
  location: class MainActivity
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.`

**Comment by owens-ben** [comment]
Seeing this in React Native version 0.72.3

**Comment by hesskav** [comment]
Same issue

**Comment by GuillaumeD-dougs** [comment]
Same issue with:
- "expo": "49.0.7"
- "react": "18.2.0",
- "react-native": "0.72.3",
- "react-native-reanimated": "3.3.0",

**Comment by hesskav** [comment]
This’ what worked for me

upgraded to reanimated 3.4.0
then deleted node_modules
then run:

npm install

deleted android & ios directories (I’m using prebuild)

then rebuilt

the warning still appears but reanimated works, I guess the warning can be ignored.

**Comment by RoJoHub** [comment]
Anu Update?

**Comment by piaskowyk** [comment]
According to my previous comment: https://github.com/software-mansion/react-native-reanimated/issues/4742#issuecomment-1667698564
> Is anyone able to provide a reproduction? Without this, we are unable to help :/

If anyone provides a repro, I will be more than happy to reopen this issue 🫡

**Comment by piaskowyk** [comment]
@11joselu thanks for providing a repo! 🙌 I tried to reproduce on you repo but it seems to work for me:
<img width="1182" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/36106620/8e6cffda-113f-41be-bf28-1ea2e49c7049">

Did you received message "No AAR for react-native-reanimated found. Attempting to build from source." during building?
If you want we can make a quick call on discord/google meet, to check what is your problem.

**Comment by masterRokshi** [comment]
@piaskowyk yep the error comes during building :)

**Comment by wegory** [comment]
Any update on this? Facing the same issue

**Comment by moedeveloper** [comment]
having same issue any update :( ? ?

**Comment by johnchiout** [comment]
Yeah me too, i am struggling with this. Any updates?

**Comment by salman-naheed** [comment]
I was able to solve the issue by defining the cmake.dir path along with sdk.dir in android -> local.properties.
sdk.dir = /home/my-pc/android-sdk
cmake.dir=/home/my-pc/android-sdk/cmake/3.19.1

**Comment by keinar** [comment]
the same for me. updates?

**Comment by amfredfred** [comment]
if it didn't throw any error or stop job, just hang on it will build...

**Comment by osasido** [comment]
encouting the same problem as well

**Comment by erickfy** [comment]
the same as well

**Comment by brunogonncalves** [comment]
same problem here, it seems many people are experiencing this issue, this shouldn't be closed!

**Comment by zouinekh** [comment]
any updates !!

**Comment by aleksamrakovic** [comment]
same react-native 0.72.15 and reanimated 3.4.0

**Comment by gmartpad** [comment]
Happening with me too. Any updates?

**Comment by vimi123** [comment]
> same react-native 0.72.15 and reanimated 3.4.0

same issue

**Comment by mad-lad1** [comment]
Sam here

**Comment by steebtom** [comment]
Battling the same issue. I tried a few different versions 3.4.0, 3.3.0 and the latest at the time of writing.

**Comment by Syedanas007** [comment]
am also facing the same issue Bruh @piaskowyk its would be helpful if you give a solution 
 "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "^0.65.1",
    "react-native-reanimated": "^2.2.4",

**Comment by steebtom** [comment]
For Expo users, this solved the issue for me.:

1.  Delete node_modules
2. `npm i`
3. `npx expo install --check` to see if you are on the recommended version of expo packages.
4. `npx expo install --fix` unless you have to be on a specific version of a package.
5. `npx expo prebuild --clean`
6. `npx expo start --clear`

Reference: [AAR](https://developer.android.com/studio/projects/android-library)

**Comment by p8ul** [comment]
Running `./gradlew clean` fixed my issue.
