### ISSUE TITLE
[android] Expo 43 does not work with reanimated 2.3.0

### ISSUE THREAD

**Issue by Mordag** [software-mansion/react-native-reanimated#2724]
## Description

Android is not compiling with 2.3.0 anymore.

### Expected behavior

No build errors.

### Actual behavior & steps to reproduce

```
[my-path-to-node-modules]/node_modules/react-native-reanimated/android/expo/src/main/java/expo/modules/adapters/reanimated/EXReanimatedPackage.java:18: error: <anonymous expo.modules.adapters.reanimated.EXReanimatedPackage$1> is not abstract and does not override abstract method getBundleAssetName(boolean) in ReactNativeHostHandler
    final ReactNativeHostHandler handler = new ReactNativeHostHandler() {
```

## Package versions

- React Native: 0.66.3
- React Native Reanimated: 2.3.0
- NodeJS: 
- Xcode:
- Java & Gradle: Java 8 using Gradle 7.3.1
- Expo: 43.0.3

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by TomCorvus** [comment]
https://github.com/software-mansion/react-native-reanimated/issues/2707

**Comment by kkafar** [comment]
See #2707, as mentioned above
