### ISSUE TITLE
iOS/Android Compile fails on react native 0.78.0

### ISSUE THREAD

**Issue by oleksandrditkovskyi** [software-mansion/react-native-reanimated#7061]
### Description

```
No member named 'parentShadowView' in 'facebook::react::ShadowViewMutation'
``` 

![Image](https://github.com/user-attachments/assets/5fad496c-1c17-47fe-9f31-6b30ece49d82)

### Steps to reproduce

Attempt to build an IOS project on RN 0.78.0 with the new architecture and the latest version of react-native-reanimated

### Snack or a link to a repository

https://snack.expo.dev/@oleksandrditkovskyi/reanimated-fail

### Reanimated version

3.16.7

### React Native version

0.78.0

### Platforms

iOS, Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

None

### Device

iOS simulator

### Device model

iPhone 16 Pro

### Acknowledgements

Yes

**Comment by polovi** [comment]
android is broken too
```
node_modules/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsUtils.cpp:34:23: error: no member named 'parentShadowView' in 'facebook::react::ShadowViewMutation'
   34 |   if (tag != mutation.parentShadowView.tag) {
      |              ~~~~~~~~ ^
```

**Comment by MatiPl01** [comment]
Hey guys!

We haven't added support for `0.78` yet. We are planning to release a new version with `0.78` support within a few new days, to stay tuned.

**Comment by H4mxa** [comment]
+1

**Comment by jonsully1** [comment]
+1

**Comment by ReeturajThakur07** [comment]
Looking forward for support of same

**Comment by trickyc0d3r** [comment]
And same problem for android

**Comment by jsuiker** [comment]
same

**Comment by valery-lavrik** [comment]
@MatiPl01   when can we expect the new version approximately?

**Comment by MatiPl01** [comment]
> [@MatiPl01](https://github.com/MatiPl01) when can we expect the new version approximately?

I hope that it will happen this week but we have to resolve a few issues beforehand. [Here](https://github.com/software-mansion/react-native-reanimated/pull/7065) is a draft that I am currently working on.

**Comment by tobua** [comment]
It's already working with the 3.17.0 release that just came out 🎉 This despite the draft PR above still open...

**Comment by MatiPl01** [comment]
`3.17.0` doesn't have `0.78` support yet. We are planning to release it in `3.17.1` within a few days.

**Comment by H4mxa** [comment]
Hey devs, could you please provide an update on when a fix might be available?

**Comment by louicoder** [comment]
> Hey devs, could you please provide an update on when a fix might be available?

@MatiPl01 has already mentioned it will be in a few days to come... Let's just be patient

**Comment by MatiPl01** [comment]
Hey guys!
Reanimated `3.17.1` with RN 0.78 has been just released. You can test it out and let me know if everything works as expected after the upgrade.

**Comment by oleksandrditkovskyi** [comment]
> Hey guys! Reanimated `3.17.1` with RN `0.78` support has been just released. You can test it out and let me know if everything works as expected after the upgrade.

Just tested it with RN 0.78, and everything compiled successfully. Thanks for the update!

**Comment by MatiPl01** [comment]
@oleksandrditkovsky Thanks for information. Since the problem no longer occurs, I will close this issue.

**Comment by kirx76** [comment]
> Hey guys! Reanimated `3.17.1` with RN `0.78` support has been just released. You can test it out and let me know if everything works as expected after the upgrade.

What a beautiful timing, just ended my transfer from RN 0.72 to 0.78 and meet that error...

**Comment by empro-narendervaddepelly** [comment]
I'm still getting error with RN 0.78.1 with ` "react-native-reanimated": "^3.17.1",`

```"dependencies": {
    "@react-navigation/native": "^7.0.18",
    "@react-navigation/native-stack": "^7.3.2",
    "react": "19.0.0",
    "react-native": "0.78.1",
    "react-native-gesture-handler": "^2.24.0",
    "react-native-reanimated": "^3.17.1",
    "react-native-screens": "^4.9.2",
    "react-native-ui-lib": "^7.39.0",
  },
```

Errors: 

```
console.js:654 Warning: TypeError: Cannot read property 'AnimatedView' of undefined

This error is located at:
    at LoginScreen (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&lazy=true&min…y=false&runModule=true&excludeSource=true&sourcePaths=url-server:115183:90)
    at StaticContainer (
```

```
LoginScreen.tsx:54 ReferenceError: Property '_WORKLET' doesn't exist, js engine: hermes Error Component Stack:
    at LoginScreen (10.0.2.2:8081/index.…rl-server:115183:90)
```

<img width="397" alt="Image" src="https://github.com/user-attachments/assets/d28cabed-8338-4f8c-b1d6-5b2da1ce7ae9" />

**Comment by omatt** [comment]
I also encountered an error using react-native-animated 3.17.1 with react-native 0.78.1. I downgraded react-native to 0.78.0 for now as a workaround.

```
> Configure project :react-native-reanimated
Android gradle plugin: 8.8.0
Gradle: 8.12
WARNING: The specified Android SDK Build Tools version (33.0.0) is ignored, as it is below the minimum supported version (35.0.0) for Android Gradle Plugin 8.8.0.
Android SDK Build Tools 35.0.0 will be used.
To suppress this warning, remove "buildToolsVersion '33.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (35.0.0) for Android Gradle Plugin 8.8.0.
Android SDK Build Tools 35.0.0 will be used.
To suppress this warning, remove "buildToolsVersion '27.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (35.0.0) for Android Gradle Plugin 8.8.0.
Android SDK Build Tools 35.0.0 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:dataBindingMergeDependencyArtifactsDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.12/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
12 actionable tasks: 1 executed, 11 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Failed to transform react-android-0.78.1-debug.aar (com.facebook.react:react-android:0.78.1) to match attributes {artifactType=android-databinding, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for JetifyTransform: /Users/$USER/.gradle/caches/modules-2/files-2.1/com.facebook.react/react-android/0.78.1/c20bcc813f6908645244e8543e92d0385a335577/react-android-0.78.1-debug.aar.
         > Java heap space

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 8s
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'. > Failed to transform react-android-0.78.1-debug.aar (com.facebook.react:react-android:0.78.1) to match attributes {artifactType=android-databinding, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}. > Execution failed for JetifyTransform: /Users/$USER/.gradle/caches/modules-2/files-2.1/com.facebook.react/react-android/0.78.1/c20bcc813f6908645244e8543e92d0385a335577/react-android-0.78.1-debug.aar. > Java heap space * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org. BUILD FAILED in 8s.
```

**Comment by empro-narendervaddepelly** [comment]
It was fixed after following these [steps](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started/#step-2-add-reanimateds-babel-plugin)

**Comment by ShadyElsharnoby** [comment]
I installed the latest version of React Native 0.78 and the latest version of Reanimated 3.17.1, but I can't generate an APK on my Macbook pro M3.
https://github.com/software-mansion/react-native-reanimated/issues/7323

**Comment by devAdrish** [comment]
My Setup:

```
"react-native": "0.76.5",
"react-native-screens": "4.6.0",
"react-native-reanimated": "^3.16.0"
```

This has been working fine for last 6 months then just yesterday I started facing this issue after running
```
yarn install
pod install --repo-update
```

Updating to newer versions didn't work and I also tried cleaning caches, deleting derived data, reinstalling node modules and pods etc, and even restarted my pc. So basically none of above solutions worked for me.

Then I downgraded reanimated to v.3.14.0 which made the app to run (build successful) however my bottom sheet broke (I am using @gorhom/bottomsheet)

So I upgraded back to "react-native-reanimated": "3.16.1". Note that I removed version range selector and went with minimum patch version I could and somehow this worked. 

**I have no idea what sorcery is this 😖**
