### ISSUE TITLE
TypeError: ReanimatedModule.installTurboModule is not a function

### ISSUE THREAD

**Issue by kokosky93** [software-mansion/react-native-reanimated#3130]
## Description

Following error is beeing thrown when try to use createAnimatedComponent method

Error: Requiring module "node_modules\react-native-reanimated\src\createAnimatedComponent.tsx", which threw an exception: TypeError: ReanimatedModule.installTurboModule is not a function

except adding
plugins: ['react-native-reanimated/plugin']
is there anything I have to do regarding to the package configuration?

## Snack or minimal code example

import Animated from 'react-native-reanimated'

Animated.createAnimatedComponent(HStack)

It applies to other methods as well. For example

useSharedValue(0)

throws the same exception.

## Package versions

+-- @babel/core@7.17.8
+-- @react-navigation/drawer@6.4.1
+-- @react-navigation/native@6.0.10
+-- @types/react@17.0.43
+-- @types/react-native@0.64.24
+-- @types/shortid@0.0.29
+-- expo@44.0.6
+-- expo-linking@3.0.0
+-- expo-status-bar@1.2.0
+-- moti@0.17.1
+-- native-base@3.3.10
+-- prettier@2.6.1
+-- react@17.0.1
+-- react-dom@17.0.1
+-- react-native@0.64.3
+-- react-native-checkbox-reanimated@0.1.1
+-- react-native-gesture-handler@2.3.2
+-- react-native-reanimated@2.5.0
+-- react-native-safe-area-context@4.2.4
+-- react-native-screens@3.13.1
+-- react-native-svg@12.3.0
+-- react-native-web@0.17.1
+-- shortid@2.2.16
+-- styled-components@5.3.5
+-- styled-system@5.1.5
`-- typescript@4.3.5

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |         0.64.3
| react-native-reanimated              |         2.5.0
| NodeJS                               |         14.16.1
| expo                                 |         44.0.6

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by kokosky93** [comment]
I fixed thath issue by installing ract-native-reanimated with expo command instead of npm. However now I see the following error:
TypeError: _reactNativeReanimated.Easing.bezier(...) is not a function
However it doesnt make sense to me as there is no type error in the code and bazier function exists

**Comment by Cookizza** [comment]
I am also getting this lately while running jest tests.

"react-native-reanimated": "^2.3.2",
"jest": "^26.6.3",

**Comment by arron-olio** [comment]
Also getting this on iOS when upgrading from version 1.9.0 -> 2.8.0

**Comment by orhangazi** [comment]
I am also getting on version 2.8.0

**Comment by FrederickEngelhardt** [comment]
Same issue.

**Comment by MathisBarre** [comment]
Same issue with react-native-reanimated 2.8.0 on iOS. I suspect cocoapods 1.11.3 🤔

**Comment by nialldbarber** [comment]
I'm getting the same issue upgrading as well. 

I tried going to `2.8.0` and also `2.6.0` as I need to ensure support for Gradle `7`+, which looks like it came in [this release](https://github.com/software-mansion/react-native-reanimated/releases/tag/2.6.0). 

We were previously on `1.9.0`, but need to upgrade reanimated as we are upgrading react native. 

Here are some _hopefully_ relevant deps we use: 

```
"@react-navigation/bottom-tabs": "5.11.15",
"@react-navigation/compat": "5.3.20",
"@react-navigation/drawer": "5.12.9",
"@react-navigation/native": "5.9.8",
"@react-navigation/stack": "5.14.9",
"react": "17.0.1",
"react-native": "0.64.2", <- going up to version `0.65.2` soon
"react-native-draggable-flatlist": "3.1.1",
"react-native-gesture-handler": "1.10.3",
"react-native-reanimated": "2.6.0",
```

**Comment by rexwalawala** [comment]
Did anyone have idea about how to fix this issue? With 2.8.0, I keep getting this error. Any help would be greatly appreciated!

**Comment by kevu-ml** [comment]
I'm still getting the same error. There has to be a way to get around this issue?

**Comment by christophehurpeau** [comment]
It might help someone: we updated expo to 45 but jest-expo was still in 44. Updating to 45 fixed this issue for us.

**Comment by ricardo-alan** [comment]
I was facing the same issue and I solved with this mock in my `jest.setup.js`

```
jest.mock('react-native', () => {
  const RN = jest.requireActual('react-native');
  RN.NativeModules.ReanimatedModule.installTurboModule = function () {};
  return RN;
});
```

**Comment by shamilovtim** [comment]
Getting this on Detox. Mocking is not an option for obvious reasons

**Comment by bryce0516** [comment]
"expo": "~44.0.0",
    "react-native-reanimated": "~2.9.1"
react-native-reanimated: 2.8.0 same issue but 2.9.1 solved this problem

**Comment by iSaBo96** [comment]
I have the same issue and nothing helps

**Comment by swatantragoswami09** [comment]
i am also having the same issue

**Comment by brianangulo** [comment]
Same same

**Comment by eeshabarua** [comment]
Same here

**Comment by lucas5g** [comment]
Same

**Comment by Goeckner** [comment]
Same issue when running ios

**Comment by yash-visit** [comment]
same issue with reanimated 2.14.4 for react native version 0.66.3

**Comment by yxwandroid** [comment]
Same here

**Comment by turgay2317** [comment]
Is there any update about the issue?

**Comment by anil-eeposit** [comment]
Any update on this. Currently facing this when upgrading reanimated to 3.5.4 on a brownfield app

**Comment by see3p00** [comment]
Has this problem been resolved？

**Comment by gopikamurali** [comment]
TypeError: ReanimatedModule.installTurboModule is not a function. (In 'ReanimatedModule.installTurboModule()', 'ReanimatedModule.installTurboModule' is undefined)
 
 i have the same issue in react native version 71.14
 and reanimated version 3.5.4

**Comment by dasler-fw** [comment]
try "react-native-reanimated": "3.15.5",

**Comment by patrycjakalinska** [comment]
hi guys! When updating please refer to out [Compatilibty Table](https://docs.swmansion.com/react-native-reanimated/docs/guides/compatibility/). This problem doesn't exist on latest Expo, or latest clean RN app with Reanimated `3.18.0`. 

I'll close this issue for now, if you have any further problems please let me know and I'll reopen.
