### ISSUE TITLE
_reactNativeReanimated.Easing.bezier is not a function _reactNativeReanimated.Easing.bezier is an instance of Object after upgrading to 2.3.1

### ISSUE THREAD

**Issue by jeyhk** [software-mansion/react-native-reanimated#2766]
## Description

After upgrading my expo project from sdk43 to 44. 
This error came up.

_reactNativeReanimated.Easing.bezier(0.16, 1, 0.3, 1) is not a function _reactNativeReanimated.Easing.bezier(0.16, 1, 0.3, 1) is an instance of Object  

### Expected behavior
should be running just like before
### Actual behavior & steps to reproduce
breaking

## Steps to reproduce
...

    const animatedBoxProps = useAnimatedProps(
    () => ({
      stroke: interpolateColor(
        Easing.bezier(0.16, 1, 0.3, 1)(progress.value),
        [0, 1],
        [boxOutlineColor, highlightColor],
        'RGB'
      ),
      fill: interpolateColor(
        Easing.bezier(0.16, 1, 0.3, 1)(progress.value),
        [0, 1],
        ['#00000000', highlightColor],
        'RGB'
      )
    }),
    [highlightColor, boxOutlineColor]
  );        

## Package versions
-reanimated: 2.3.1

- React Native Reanimated: 2.3.1

**Comment by felipevlima** [comment]
I have the same error.

**Comment by Ediigas** [comment]
estou com esse error

**Comment by felipevlima** [comment]
> estou com esse error

Look, what I did was to downgrade the expo sdk from version 44 to 43 and downgrade the other packages for compatibility and it started working again.

**Comment by lehaidangdev** [comment]
> > estou com esse error
> 
> Look, what I did was to downgrade the expo sdk from version 44 to 43 and downgrade the other packages for compatibility and it started working again.

May I know which packages you have downgraded to? react-native-reanimated, react-native-gesture-handler, ...
Many thanks

**Comment by felipevlima** [comment]
> 
Yes, in my case i need to downgrade this package:
    "expo": "43.0.0",
    "expo-linking": "2.4.2",
    "expo-status-bar": "1.1.0",
    "react-native-gesture-handler": "1.10.2",
    "react-native-reanimated": "2.2.0",
    "react-native-screens": "3.8.0",

When you start your project after downgrade expo to 43, you will see a warning talking about this packages

**Comment by jeyhk** [comment]
> > 
> 
> Yes, in my case i need to downgrade this package: "expo": "43.0.0", "expo-linking": "2.4.2", "expo-status-bar": "1.1.0", "react-native-gesture-handler": "1.10.2", "react-native-reanimated": "2.2.0", "react-native-screens": "3.8.0",
> 
> When you start your project after downgrade expo to 43, you will see a warning talking about this packages

How can you downgrade the expo sdk ? , cant find a good guide.

**Comment by eyousefifar** [comment]
same issue here

**Comment by felipevlima** [comment]
> > > 
> > 
> > 
> > Yes, in my case i need to downgrade this package: "expo": "43.0.0", "expo-linking": "2.4.2", "expo-status-bar": "1.1.0", "react-native-gesture-handler": "1.10.2", "react-native-reanimated": "2.2.0", "react-native-screens": "3.8.0",
> > When you start your project after downgrade expo to 43, you will see a warning talking about this packages
> 
> How can you downgrade the expo sdk ? , cant find a good guide.

Hey,,, to downgrade expo sdk, only change the version on package.json, delete lock file and node_modules and install all again. 
Check if in expo when you change version, you remove "ˆ" symbol.
After that, every time when you start project, you will se warning saying expo has a new version to install.
In my case, only this make all work fine

**Comment by pivey** [comment]
same issue here, i'm not using expo in my RN app, just ran into this issue today after upgrading to react-native-reanimated: 2.3.0.

Does anyone have ideas for how to solve this for apps that don't use expo??

**Comment by piaskowyk** [comment]
Hey, I changed the implementation of `Easing.bezier` but I forgot about TypeScript. I prepared PR with fix: https://github.com/software-mansion/react-native-reanimated/pull/2792 but if you need hotfix you should use something like this:
```js
(Easing.bezier(0.16, 1, 0.3, 1).factory)()(0.2)
```

**Comment by notsuhas** [comment]
Hey, any ETA on the fix being pushed to the npm package?

**Comment by TTelkdotcom** [comment]
is there any update on when the typescript support will come?

**Comment by Bruce-Ming** [comment]
2.4.1 same issue here

**Comment by Cookizza** [comment]
If you are getting this issue on latest reanimated 2.3 or .4 then you have the option to change your function from `bezier()` to `bezierFn()` to continue compatibility with your old code. It will then work as before.

This is mentioned here https://github.com/software-mansion/react-native-reanimated/pull/2792

**Comment by kokosky93** [comment]
guys I have the same issue. I had to change version of this package to fit my expo version because a strange error was throw by this package and now I see in the console following error:
TypeError: _reactNativeReanimated.Easing.bezier(...) is not a function

Hovewer there is no type error. Bezier() function exists..

I have no idea what is going on. Any suggestions?

**Comment by kokosky93** [comment]
How this is fixed? This is not fixed. It still doesn't work.

**Comment by kevnoutsawo** [comment]
I am having this same issue. I tried using bezierFn but it isn't recognized. I am using reanimated 2.3.1.
When using reanimated, the project seems to break every time you update another package like expo.
It feels like walking on eggshells as something is always about to break. Is reanimated production ready yet?
If it is going to break the whole project every once in a while and for obscure reasons, then it will be a nightmare to maintain a project with reanimated in it.

**Comment by Userkozmin** [comment]
I am getting error as well, also for useTransition.
"_reactNativeReanimated.useTransition is not a function"

**Comment by lopesboa** [comment]
any update about this issue, still getting this error, and i'm not using expo.
`"react-native-reanimated": "2.13.0",`
`"react-native-gesture-handler": "^2.9.0",`

**Comment by DominicGBauer** [comment]
For anyone facing this issue when using jest this answer solved it for me https://stackoverflow.com/a/68956430
Add to `jest-setup.js`:

```jsx
import { Animated } from 'react-native';

Animated.timing = () => ({
    start: () => jest.fn(),
});
```

**Comment by RadekKosiada** [comment]
> For anyone facing this issue when using jest this answer solved it for me https://stackoverflow.com/a/68956430 Add to `jest-setup.js`:
> 
> ```js
> import { Animated } from 'react-native';
> 
> Animated.timing = () => ({
>     start: () => jest.fn(),
> });
> ```

Thank you, but I am still facing it and it didn't help 
`"react-native-reanimated": "^3.1.0",`
`"react-native-gesture-handler": "^2.8.0",`
