### ISSUE TITLE
[Reanimated 3.3.0] runOnJs crash - "Object is not a function"

### ISSUE THREAD

**Issue by AlexanderEggers** [software-mansion/react-native-reanimated#4613]
### Description

I have updated my project from 2.17.0 to 3.3.0 and I am running into an issue in the following scenario:

```typescript
const finishTransition = useCallback(
    (
      resolve: (value: void | PromiseLike<void>) => void,
    ) => {
       // ... some logic, not important to understand the issue
      resolve();
    },
    [onFinishedTransitioning]
  );

const handlePress = () => {
    new Promise(resolve => {
      scale.value = withSpring(2, {}, () => {
        runOnJS(finishTransition)(resolve);
      });
    }).then(() => {
      // ...
    });
  };
```

Calling the resolve within finishTransition using runOnJS was working fine in 2.17.0. In 3.3.0 is is throwing `TypeError: Object is not a function`. I had a closer look and the resolve parameter of the finishTransition function is logged as "{"__remoteFunction": {}}". There seems to be an incorrect translation happening.

### Steps to reproduce

1. Follow the description to create a code example similar to how I defined it. It seems to be related to passing a promise resolve function into the runOnJs function.

### Snack or a link to a repository

https://github.com/AlexanderEggers/ReanimatedIssue

### Reanimated version

3.3.0

### React Native version

0.71.11

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hey @AlexanderEggers, thanks for reporting this problem! I was able to successfully reproduce the issue on the repro you have provided. Could you please check if PR #4617 fixes the issue for you?

**Comment by AlexanderEggers** [comment]
@tomekzaw Thanks the fix in the PR works well for me 🙌

**Comment by AlexanderEggers** [comment]
@tomekzaw I did some more testing and I noticed that this bug is still happening in release builds. It is running fine in debug builds builds but something is not handled properly because of either hermes or proguard.

**Comment by tomekzaw** [comment]
@AlexanderEggers thanks for letting me know, I will take a look on it.

**Comment by RalissonMattias** [comment]
+1

**Comment by tomekzaw** [comment]
@AlexanderEggers I've pushed e76311f05c661787ffcc14bb9ab71d7403d680e7 which should fix the issue in the release mode. Could you please check if it works for you?

**Comment by AlexanderEggers** [comment]
@tomekzaw The changes work fine in debug and release builds. Thank you :)

**Comment by hadnet** [comment]
I was getting the same error, tried to apply the PR https://github.com/software-mansion/react-native-reanimated/pull/4617 from @tomekzaw but did not work because the isRemoteFunctionShareableClone function that crashes the app. Using the little change below from @AlexanderEggers now works and solves my issue:

```diff
+ if (value.__remoteFunction) {
+    return value.__remoteFunction;
+ }
```

**Comment by AlexanderEggers** [comment]
@tomekzaw Do you have any updates around getting the related PR into an upcoming stable version?

**Comment by tomekzaw** [comment]
@tjzel promised to take a look at it soon

**Comment by josej14** [comment]
Hi guys! @tjzel @tomekzaw We are facing an issue with `RunOnJS` method after your fix on `v3.5.0`. Specifically, we are using reanimated `v3.5.2`. When we pass a function (`dispatch` from  `redux v4.2.0`) to `RunOnJS(ourMethod)(dispatch)` seems that your fix works on debug but not in production.

We captured this error log:

```
!object.isHostObject<ShareableJSRef>(rt) && "[Reanimated] Provided value is already an instance of ShareableJSRef." > Assertion failed: (!object.isHostObject<ShareableJSRef>(rt) && "[Reanimated] Provided value is already an instance of ShareableJSRef."), function makeShareableClone, file Shareables.cpp, line 71.
 > makeShareableClone > Shareables.cpp
```

Any idea of what could be the cause of this problem? Thanks!

**Comment by tjzel** [comment]
@josej14 Try it on 3.5.4 :)

**Comment by AlexanderEggers** [comment]
@tjzel @tomekzaw - The example project (https://github.com/AlexanderEggers/ReanimatedIssue) in the initial entry of this issue and it is indeed crashing on 3.5.4 again. It seems like some of the most recent changes in the shareable.ts is causing that.

One of these commits probably:
- b70ef886816b4e3daa492279923d797cf703450c
- a47eb0a3413daade0e15a636f8b193c18320c0bb

**Comment by tomekzaw** [comment]
@AlexanderEggers @josej14 You're right, the issue still persists, although now the cause of the error is different.

Could you please check if #5264 works for you?

**Comment by AlexanderEggers** [comment]
@tomekzaw That is resolving the issue for me. Thank you! When do you think this will be part of a regular release?

**Comment by tomekzaw** [comment]
We'll do our best to deliver it in 3.6.0. There's still a few PRs that need to be merged prior to a release but fingers crossed it will be like next week.

**Comment by jenskuhrjorgensen** [comment]
> We'll do our best to deliver it in 3.6.0. There's still a few PRs that need to be merged prior to a release but fingers crossed it will be like next week.

Hi @tomekzaw :)
I'm still desperately waiting for this fix along with some other TS fixes - are there any plans for a v3.6.0 release anytime soon? I can see that you have more than 10% of your v3 users running on [nightly versions](https://www.npmjs.com/package/react-native-reanimated?activeTab=versions) of the lib - probably because it has been quite a while since the last release.

**Comment by tomekzaw** [comment]
@jenskuhrjorgensen actually we're working on last fixes, fingers crossed we'll release 3.6.0 early next week (or even today if all goes well).

**Comment by tomekzaw** [comment]
@jenskuhrjorgensen FYI react-native-reanimated@3.6.0 has just been released.

**Comment by HarshitMadhav** [comment]
@tomekzaw thanks! I was facing this same issue and I can confirm, this issue is fixed in react-native-reanimated@3.6.0
