### ISSUE TITLE
1.13.4+ fails to build with RN 0.70.0

### ISSUE THREAD

**Issue by xchwarze** [software-mansion/react-native-reanimated#3550]
### Description

1.13.4 version compilation error with RN 0.70

### Steps to reproduce

1. npx react-native init test
2. cd test && yarn add https://github.com/software-mansion/react-native-reanimated#c4a6b6f687ede090f6081064abe83a2ef9a05784
3. cd android && ./gradlew assembleRelease

### Snack or a link to a repository

https://github.com/xchwarze/react-native-reanimated-v1

### Reanimated version

1.13.4

### React Native version

0.70.0

### Platforms

Android

### Acknowledgements

Yes

**Comment by xchwarze** [comment]
fixed in https://github.com/software-mansion/react-native-reanimated/pull/3551

**Comment by piaskowyk** [comment]
Unfortunately, we dropped the support for Reanimated 1. If someone facing this issue we highly recommend the upgrade to the latest version of reanimated or applying [this patch](https://github.com/software-mansion/react-native-reanimated/pull/3551) manually by for example [patch package tool](https://www.npmjs.com/package/patch-package)
